/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type ArrayType<T> = ArrayTypeImpl<T> extends (infer U)[]
  ? U[]
  : ArrayTypeImpl<T>;

export type ArrayTypeImpl<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S[], I[], U[]>
  : T[];

export type DocumentTypeEnum = "ci_uy" | "dni_ar" | "passport";

export type EventImageType = "flyer" | "hero";

export type EventTicketCurrency = "USD" | "UYU";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type InvoiceParty = "buyer" | "seller";

export type InvoiceStatus = "failed" | "issued" | "pending";

export type JobStatus = "completed" | "failed" | "pending" | "processing";

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type NotificationBatchStatus = "cancelled" | "pending" | "processed";

export type NotificationChannel = "email" | "in_app" | "sms";

export type NotificationStatus = "failed" | "pending" | "seen" | "sent";

export type NotificationType = "auth_invitation" | "auth_new_device_sign_in" | "auth_password_changed" | "auth_password_removed" | "auth_primary_email_changed" | "auth_reset_password_code" | "auth_verification_code" | "buyer_ticket_cancelled" | "document_reminder" | "document_uploaded" | "document_uploaded_batch" | "identity_verification_completed" | "identity_verification_failed" | "identity_verification_manual_review" | "identity_verification_rejected" | "order_confirmed" | "order_expired" | "order_invoice" | "payment_failed" | "payment_succeeded" | "payout_cancelled" | "payout_completed" | "payout_failed" | "payout_processing" | "seller_earnings_retained" | "ticket_sold_seller";

export type Numeric = ColumnType<string, number | string, number | string>;

export type OrderStatus = "cancelled" | "confirmed" | "expired" | "pending";

export type OrderTicketReservationStatus = "active" | "cancelled" | "refund_pending" | "refunded";

export type PaymentEventType = "chargeback_received" | "dispute_opened" | "dispute_resolved" | "fraud_check_failed" | "manual_review_required" | "payment_created" | "refund_completed" | "refund_initiated" | "status_change" | "status_synced" | "webhook_received";

export type PaymentMethod = "bank_transfer" | "cash" | "credit_card" | "debit_card" | "other" | "pix" | "voucher";

export type PaymentProvider = "dlocal" | "mercadopago" | "paypal" | "stripe";

export type PaymentStatus = "cancelled" | "expired" | "failed" | "paid" | "partially_refunded" | "pending" | "processing" | "refunded";

export type PayoutEventType = "admin_processed" | "cancelled" | "payout_requested" | "status_change" | "transfer_completed" | "transfer_failed" | "transfer_initiated";

export type PayoutStatus = "cancelled" | "completed" | "failed" | "pending" | "processing";

export type PayoutType = "paypal" | "uruguayan_bank";

export type QrAvailabilityTiming = "12h" | "24h" | "3h" | "48h" | "6h" | "72h";

export type SellerEarningsRetainedReason = "dispute" | "fraud" | "missing_document" | "other";

export type SellerEarningsStatus = "available" | "failed_payout" | "paid_out" | "payout_requested" | "pending" | "retained";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "organizer" | "user";

export type VerificationStatusEnum = "completed" | "failed" | "pending" | "rejected" | "requires_manual_review";

export interface EventImages {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  displayOrder: Generated<number>;
  eventId: string;
  id: Generated<string>;
  imageType: EventImageType;
  url: string;
}

export interface Events {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  description: string | null;
  eventEndDate: Timestamp;
  eventStartDate: Timestamp;
  externalId: string;
  externalUrl: string;
  id: Generated<string>;
  lastScrapedAt: Generated<Timestamp>;
  metadata: Json | null;
  name: string;
  platform: string;
  qrAvailabilityTiming: QrAvailabilityTiming | null;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
  venueId: string | null;
}

export interface EventTicketWaves {
  createdAt: Generated<Timestamp>;
  currency: EventTicketCurrency;
  deletedAt: Timestamp | null;
  description: string | null;
  eventId: string;
  externalId: string;
  faceValue: Numeric;
  id: Generated<string>;
  isAvailable: Generated<boolean>;
  isSoldOut: Generated<boolean>;
  lastScrapedAt: Generated<Timestamp>;
  metadata: Json | null;
  name: string;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface EventVenues {
  address: string;
  city: string;
  country: Generated<string>;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  googlePlaceId: string | null;
  id: Generated<string>;
  latitude: Numeric | null;
  longitude: Numeric | null;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface EventViewsDaily {
  createdAt: Generated<Timestamp>;
  date: Timestamp;
  eventId: string;
  id: Generated<string>;
  updatedAt: Generated<Timestamp>;
  viewCount: Generated<number>;
}

export interface Invoices {
  baseAmount: Numeric;
  createdAt: Generated<Timestamp>;
  currency: EventTicketCurrency;
  emailSentAt: Timestamp | null;
  externalId: string;
  id: Generated<string>;
  issuedAt: Timestamp | null;
  lastError: string | null;
  orderId: string;
  party: InvoiceParty;
  pdfStoragePath: string | null;
  provider: Generated<string>;
  providerResponse: Json | null;
  sellerUserId: string | null;
  status: Generated<InvoiceStatus>;
  totalAmount: Numeric;
  vatAmount: Numeric;
}

export interface Jobs {
  attempts: Generated<number>;
  completedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  error: string | null;
  id: Generated<string>;
  idempotencyKey: string | null;
  jobType: string;
  maxAttempts: Generated<number>;
  payload: Json;
  scheduledAt: Generated<Timestamp>;
  startedAt: Timestamp | null;
  status: Generated<JobStatus>;
}

export interface Listings {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  publisherUserId: string;
  soldAt: Timestamp | null;
  ticketWaveId: string;
  updatedAt: Generated<Timestamp>;
}

export interface ListingTickets {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  listingId: string;
  price: Numeric;
  soldAt: Timestamp | null;
  ticketNumber: number;
  updatedAt: Generated<Timestamp>;
}

export interface NotificationBatches {
  channels: ArrayType<NotificationChannel>;
  createdAt: Generated<Timestamp>;
  debounceKey: string;
  finalNotificationId: string | null;
  id: Generated<string>;
  notificationType: NotificationType;
  status: Generated<NotificationBatchStatus>;
  updatedAt: Generated<Timestamp>;
  userId: string;
  windowEndsAt: Timestamp;
}

export interface NotificationBatchItems {
  actions: Json | null;
  batchId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  metadata: Json;
}

export interface Notifications {
  actions: Json | null;
  channels: ArrayType<NotificationChannel>;
  channelStatus: Generated<Json | null>;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  metadata: Json | null;
  retryCount: Generated<number>;
  seenAt: Timestamp | null;
  sendViaJob: Generated<boolean>;
  status: Generated<NotificationStatus>;
  type: NotificationType;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface OrderItems {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  orderId: string;
  pricePerTicket: Numeric;
  quantity: number;
  subtotal: Numeric;
  ticketWaveId: string;
  updatedAt: Generated<Timestamp>;
}

export interface Orders {
  cancelledAt: Timestamp | null;
  confirmedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  currency: EventTicketCurrency;
  deletedAt: Timestamp | null;
  eventId: string;
  id: Generated<string>;
  platformCommission: Numeric;
  reservationExpiresAt: Timestamp;
  status: Generated<OrderStatus>;
  subtotalAmount: Numeric;
  totalAmount: Numeric;
  updatedAt: Generated<Timestamp>;
  userId: string;
  vatOnCommission: Numeric;
}

export interface OrderTicketReservations {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  listingTicketId: string;
  orderId: string;
  reservedAt: Generated<Timestamp>;
  reservedUntil: Timestamp;
  status: Generated<OrderTicketReservationStatus>;
  updatedAt: Generated<Timestamp>;
}

export interface PaymentEvents {
  createdAt: Generated<Timestamp>;
  eventData: Generated<Json | null>;
  eventType: PaymentEventType;
  fromStatus: PaymentStatus | null;
  id: Generated<string>;
  ipAddress: string | null;
  paymentId: string;
  toStatus: PaymentStatus | null;
  userAgent: string | null;
}

export interface Payments {
  amount: Numeric;
  approvedAt: Timestamp | null;
  backUrl: string | null;
  balanceAmount: Numeric | null;
  balanceCurrency: string | null;
  balanceFee: Numeric | null;
  cancelledAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  currency: string;
  deletedAt: Timestamp | null;
  exchangeRate: Numeric | null;
  expiredAt: Timestamp | null;
  failedAt: Timestamp | null;
  failureReason: string | null;
  id: Generated<string>;
  notificationUrl: string | null;
  orderId: string;
  payerCountry: string | null;
  payerDocument: string | null;
  payerDocumentType: string | null;
  payerEmail: string | null;
  payerFirstName: string | null;
  payerLastName: string | null;
  paymentMethod: PaymentMethod | null;
  provider: PaymentProvider;
  providerMetadata: Generated<Json | null>;
  providerPaymentId: string;
  redirectUrl: string | null;
  refundedAt: Timestamp | null;
  status: Generated<PaymentStatus>;
  successUrl: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface PayoutDocuments {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  documentType: Generated<string>;
  fileName: string;
  id: Generated<string>;
  mimeType: string;
  originalName: string;
  payoutId: string;
  sizeBytes: number;
  storagePath: string;
  updatedAt: Generated<Timestamp>;
  uploadedAt: Generated<Timestamp>;
  uploadedBy: string;
}

export interface PayoutEvents {
  createdAt: Generated<Timestamp>;
  createdBy: string | null;
  eventData: Generated<Json | null>;
  eventType: PayoutEventType;
  fromStatus: PayoutStatus | null;
  id: Generated<string>;
  ipAddress: string | null;
  payoutId: string;
  toStatus: PayoutStatus | null;
  userAgent: string | null;
}

export interface PayoutMethods {
  accountHolderName: string;
  accountHolderSurname: string;
  createdAt: Generated<Timestamp>;
  currency: EventTicketCurrency;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  isDefault: Generated<boolean>;
  metadata: Generated<Json | null>;
  payoutType: PayoutType;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface Payouts {
  amount: Numeric;
  completedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  currency: EventTicketCurrency;
  deletedAt: Timestamp | null;
  failedAt: Timestamp | null;
  failureReason: string | null;
  id: Generated<string>;
  metadata: Generated<Json | null>;
  notes: string | null;
  payoutMethodId: string;
  processedAt: Timestamp | null;
  processedBy: string | null;
  processingFee: Numeric | null;
  requestedAt: Generated<Timestamp>;
  sellerUserId: string;
  status: Generated<PayoutStatus>;
  transactionReference: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface RateLimit {
  count: Generated<number>;
  key: string;
  resetTime: Timestamp;
}

export interface SellerEarnings {
  createdAt: Generated<Timestamp>;
  currency: EventTicketCurrency;
  deletedAt: Timestamp | null;
  holdUntil: Timestamp;
  id: Generated<string>;
  listingTicketId: string;
  payoutId: string | null;
  retainedReason: SellerEarningsRetainedReason | null;
  sellerAmount: Numeric;
  sellerUserId: string;
  status: Generated<SellerEarningsStatus>;
  updatedAt: Generated<Timestamp>;
}

export interface TicketDocuments {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  documentType: Generated<string>;
  fileName: string;
  id: Generated<string>;
  isPrimary: Generated<boolean>;
  mimeType: string;
  originalName: string;
  sizeBytes: number;
  status: Generated<string>;
  storagePath: string;
  ticketId: string;
  updatedAt: Generated<Timestamp>;
  uploadedAt: Generated<Timestamp>;
  verifiedAt: Timestamp | null;
  verifiedBy: string | null;
  version: Generated<number>;
}

export interface Users {
  clerkId: string;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  documentCountry: string | null;
  documentImagePath: string | null;
  documentNumber: string | null;
  documentType: DocumentTypeEnum | null;
  documentVerified: Generated<boolean | null>;
  documentVerifiedAt: Timestamp | null;
  email: string;
  firstName: string | null;
  id: Generated<string>;
  imageUrl: string | null;
  lastActiveAt: Timestamp | null;
  lastName: string | null;
  manualReviewReason: string | null;
  metadata: Json | null;
  role: Generated<UserRole>;
  selfieImagePath: string | null;
  updatedAt: Generated<Timestamp>;
  verificationAttempts: Generated<number | null>;
  verificationConfidenceScores: Json | null;
  verificationMetadata: Json | null;
  verificationSessionCreatedAt: Timestamp | null;
  verificationSessionId: string | null;
  verificationStatus: Generated<VerificationStatusEnum | null>;
}

export interface VerificationAuditLogs {
  action: string;
  confidenceScores: Json | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  metadata: Json | null;
  newStatus: string | null;
  previousStatus: string | null;
  userId: string;
}

export interface DB {
  eventImages: EventImages;
  events: Events;
  eventTicketWaves: EventTicketWaves;
  eventVenues: EventVenues;
  eventViewsDaily: EventViewsDaily;
  invoices: Invoices;
  jobs: Jobs;
  listings: Listings;
  listingTickets: ListingTickets;
  notificationBatches: NotificationBatches;
  notificationBatchItems: NotificationBatchItems;
  notifications: Notifications;
  orderItems: OrderItems;
  orders: Orders;
  orderTicketReservations: OrderTicketReservations;
  paymentEvents: PaymentEvents;
  payments: Payments;
  payoutDocuments: PayoutDocuments;
  payoutEvents: PayoutEvents;
  payoutMethods: PayoutMethods;
  payouts: Payouts;
  rateLimit: RateLimit;
  sellerEarnings: SellerEarnings;
  ticketDocuments: TicketDocuments;
  users: Users;
  verificationAuditLogs: VerificationAuditLogs;
}
