/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type ArrayType<T> = ArrayTypeImpl<T> extends (infer U)[]
  ? U[]
  : ArrayTypeImpl<T>;

export type ArrayTypeImpl<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S[], I[], U[]>
  : T[];

export type DocumentTypeEnum = "ci_uy" | "dni_ar" | "passport";

export type EventImageType = "flyer" | "hero" | "og_hero";

export type EventProducerMemberRole = "manager" | "owner" | "viewer";

export type EventStatus = "active" | "cancelled" | "draft" | "finished" | "inactive" | "published" | "rejected" | "under_review";

export type EventTicketCurrency = "ARS" | "USD" | "UYU";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type InvoiceParty = "buyer" | "seller";

export type InvoiceStatus = "failed" | "issued" | "pending";

export type JobStatus = "completed" | "failed" | "pending" | "processing";

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type NotificationBatchStatus = "cancelled" | "pending" | "processed";

export type NotificationChannel = "email" | "in_app" | "sms" | "whatsapp";

export type NotificationStatus = "failed" | "pending" | "seen" | "sent";

export type NotificationType = "auth_invitation" | "auth_new_device_sign_in" | "auth_password_changed" | "auth_password_removed" | "auth_primary_email_changed" | "auth_reset_password_code" | "auth_verification_code" | "buyer_ticket_cancelled" | "document_reminder" | "document_uploaded" | "document_uploaded_batch" | "identity_verification_completed" | "identity_verification_failed" | "identity_verification_manual_review" | "identity_verification_rejected" | "order_confirmed" | "order_expired" | "order_invoice" | "payment_failed" | "payment_succeeded" | "payout_cancelled" | "payout_completed" | "payout_failed" | "payout_processing" | "seller_earnings_available" | "seller_earnings_retained" | "ticket_report_action_added" | "ticket_report_closed" | "ticket_report_created" | "ticket_report_status_changed" | "ticket_sold_seller";

export type Numeric = ColumnType<string, number | string, number | string>;

export type OrderStatus = "cancelled" | "confirmed" | "expired" | "pending";

export type OrderTicketReservationStatus = "active" | "cancelled" | "refund_pending" | "refunded";

export type PaymentEventType = "chargeback_received" | "dispute_opened" | "dispute_resolved" | "fraud_check_failed" | "manual_review_required" | "payment_created" | "refund_completed" | "refund_initiated" | "status_change" | "status_synced" | "webhook_received";

export type PaymentMethod = "bank_transfer" | "cash" | "credit_card" | "debit_card" | "other" | "pix" | "voucher";

export type PaymentProvider = "dlocal" | "mercadopago" | "stripe";

export type PaymentStatus = "cancelled" | "expired" | "failed" | "paid" | "partially_refunded" | "pending" | "processing" | "refunded";

export type PayoutEventType = "admin_processed" | "cancelled" | "payout_requested" | "provider_response" | "status_change" | "transfer_completed" | "transfer_failed" | "transfer_initiated";

export type PayoutProvider = "dlocal_go" | "manual_bank";

export type PayoutStatus = "cancelled" | "completed" | "failed" | "pending" | "processing";

export type PayoutType = "argentinian_bank" | "uruguayan_bank";

export type QrAvailabilityTiming = "12h" | "24h" | "3h" | "48h" | "6h" | "72h";

export type SellerEarningsRetainedReason = "dispute" | "fraud" | "missing_document" | "other";

export type SellerEarningsStatus = "available" | "failed_payout" | "paid_out" | "payout_requested" | "pending" | "retained";

export type TicketOwnershipTransferType = "primary_sale" | "resale" | "rrpp_invitation" | "rrpp_off_platform_sale";

export type TicketReportActionType = "close" | "comment" | "refund_full" | "refund_partial" | "reject";

export type TicketReportCaseType = "invalid_ticket" | "other" | "problem_with_seller" | "ticket_not_received";

export type TicketReportEntityType = "listing" | "listing_ticket" | "order" | "order_ticket_reservation";

export type TicketReportRefundStatus = "pending" | "refunded" | "skipped";

export type TicketReportSource = "auto_missing_document" | "user_report";

export type TicketReportStatus = "awaiting_customer" | "awaiting_support" | "closed";

export type TicketWaveAvailabilityMode = "after_previous" | "always" | "scheduled";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "organizer" | "user";

export type VerificationStatusEnum = "completed" | "failed" | "pending" | "rejected" | "requires_manual_review";

export type WaveRrppIssuanceType = "both" | "invitation" | "off_platform_sale";

export interface EventImages {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  displayOrder: Generated<number>;
  eventId: string;
  id: Generated<string>;
  imageType: EventImageType;
  thumbnailUrl: string | null;
  url: string;
}

export interface EventProducerMembers {
  acceptedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  eventProducerId: string;
  id: Generated<string>;
  invitedAt: Generated<Timestamp>;
  role: Generated<EventProducerMemberRole>;
  userId: string;
}

export interface EventProducers {
  contactEmail: string | null;
  contactPhone: string | null;
  country: string | null;
  createdAt: Generated<Timestamp>;
  defaultBuyerCommissionRate: Numeric | null;
  defaultProducerFeeAmount: Numeric | null;
  defaultProducerFeeCurrency: EventTicketCurrency | null;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  legalName: string | null;
  name: string;
  slug: string;
  taxId: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface Events {
  approvedAt: Timestamp | null;
  approvedByUserId: string | null;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  description: string | null;
  draftPayload: Json | null;
  eventEndDate: Timestamp;
  eventProducerId: string | null;
  eventStartDate: Timestamp;
  externalId: string;
  externalUrl: string;
  id: Generated<string>;
  isOfficial: Generated<boolean>;
  lastScrapedAt: Generated<Timestamp>;
  metadata: Json | null;
  name: string;
  officialResaleEnabled: Generated<boolean>;
  officialResaleMaxMarkupPercent: Numeric | null;
  platform: string;
  qrAvailabilityTiming: QrAvailabilityTiming | null;
  rejectedReason: string | null;
  slug: string;
  status: Generated<EventStatus>;
  submittedAt: Timestamp | null;
  updatedAt: Generated<Timestamp>;
  venueId: string | null;
}

export interface EventTicketWaveConfigs {
  availabilityMode: Generated<TicketWaveAvailabilityMode>;
  availableFrom: Timestamp | null;
  availableUntil: Timestamp | null;
  createdAt: Generated<Timestamp>;
  displayOrder: Generated<number>;
  eventTicketWaveId: string;
  houseListingId: string | null;
  id: Generated<string>;
  isHiddenFromSale: Generated<boolean>;
  previousWaveId: string | null;
  rrppIssuable: Generated<boolean>;
  rrppIssuanceType: Generated<WaveRrppIssuanceType>;
  stock: number;
  updatedAt: Generated<Timestamp>;
}

export interface EventTicketWaves {
  createdAt: Generated<Timestamp>;
  currency: EventTicketCurrency;
  deletedAt: Timestamp | null;
  description: string | null;
  eventId: string;
  externalId: string;
  faceValue: Numeric;
  id: Generated<string>;
  isAvailable: Generated<boolean>;
  isSoldOut: Generated<boolean>;
  lastScrapedAt: Generated<Timestamp>;
  metadata: Json | null;
  name: string;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface EventVenues {
  address: string;
  city: string;
  country: Generated<string>;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  googlePlaceId: string | null;
  id: Generated<string>;
  latitude: Numeric | null;
  longitude: Numeric | null;
  name: string;
  region: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface EventViewsDaily {
  createdAt: Generated<Timestamp>;
  date: Timestamp;
  eventId: string;
  id: Generated<string>;
  updatedAt: Generated<Timestamp>;
  viewCount: Generated<number>;
}

export interface ImpersonationLogs {
  adminUserId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  ipAddress: string;
  reason: string | null;
  targetUserId: string;
}

export interface Invoices {
  baseAmount: Numeric;
  createdAt: Generated<Timestamp>;
  currency: EventTicketCurrency;
  emailSentAt: Timestamp | null;
  externalId: string;
  id: Generated<string>;
  issuedAt: Timestamp | null;
  lastError: string | null;
  orderId: string;
  party: InvoiceParty;
  pdfStoragePath: string | null;
  provider: Generated<string>;
  providerResponse: Json | null;
  sellerUserId: string | null;
  status: Generated<InvoiceStatus>;
  totalAmount: Numeric;
  vatAmount: Numeric;
}

export interface Jobs {
  attempts: Generated<number>;
  completedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  error: string | null;
  id: Generated<string>;
  idempotencyKey: string | null;
  jobType: string;
  maxAttempts: Generated<number>;
  payload: Json;
  scheduledAt: Generated<Timestamp>;
  startedAt: Timestamp | null;
  status: Generated<JobStatus>;
}

export interface Listings {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  isHouseListing: Generated<boolean>;
  publisherEventProducerId: string | null;
  publisherUserId: string | null;
  soldAt: Timestamp | null;
  ticketWaveId: string;
  updatedAt: Generated<Timestamp>;
}

export interface ListingTickets {
  createdAt: Generated<Timestamp>;
  currentOwnerUserId: string | null;
  deletedAt: Timestamp | null;
  entryUsedAt: Timestamp | null;
  entryUsedByUserId: string | null;
  id: Generated<string>;
  listingId: string;
  originalOrderId: string | null;
  price: Numeric;
  soldAt: Timestamp | null;
  ticketNumber: number;
  updatedAt: Generated<Timestamp>;
}

export interface NotificationBatches {
  channels: ArrayType<NotificationChannel>;
  createdAt: Generated<Timestamp>;
  debounceKey: string;
  finalNotificationId: string | null;
  id: Generated<string>;
  notificationType: NotificationType;
  status: Generated<NotificationBatchStatus>;
  updatedAt: Generated<Timestamp>;
  userId: string;
  windowEndsAt: Timestamp;
}

export interface NotificationBatchItems {
  actions: Json | null;
  batchId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  metadata: Json;
}

export interface Notifications {
  actions: Json | null;
  channels: ArrayType<NotificationChannel>;
  channelStatus: Generated<Json | null>;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  metadata: Json | null;
  retryCount: Generated<number>;
  seenAt: Timestamp | null;
  sendViaJob: Generated<boolean>;
  status: Generated<NotificationStatus>;
  type: NotificationType;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface OrderItems {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  orderId: string;
  pricePerTicket: Numeric;
  quantity: number;
  subtotal: Numeric;
  ticketWaveId: string;
  updatedAt: Generated<Timestamp>;
}

export interface Orders {
  cancelledAt: Timestamp | null;
  confirmedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  currency: EventTicketCurrency;
  deletedAt: Timestamp | null;
  eventId: string;
  id: Generated<string>;
  platformCommission: Numeric;
  reservationExpiresAt: Timestamp;
  status: Generated<OrderStatus>;
  subtotalAmount: Numeric;
  totalAmount: Numeric;
  updatedAt: Generated<Timestamp>;
  userId: string;
  vatOnCommission: Numeric;
}

export interface OrderTicketReservations {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  listingTicketId: string;
  orderId: string;
  reservedAt: Generated<Timestamp>;
  reservedUntil: Timestamp;
  status: Generated<OrderTicketReservationStatus>;
  updatedAt: Generated<Timestamp>;
}

export interface OtpVerifications {
  attempts: Generated<number>;
  codeHash: string;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  phoneNumber: string;
  userId: string;
  verified: Generated<boolean>;
}

export interface PaymentEvents {
  createdAt: Generated<Timestamp>;
  eventData: Generated<Json | null>;
  eventType: PaymentEventType;
  fromStatus: PaymentStatus | null;
  id: Generated<string>;
  ipAddress: string | null;
  paymentId: string;
  toStatus: PaymentStatus | null;
  userAgent: string | null;
}

export interface Payments {
  amount: Numeric;
  approvedAt: Timestamp | null;
  backUrl: string | null;
  balanceAmount: Numeric | null;
  balanceCurrency: string | null;
  balanceFee: Numeric | null;
  cancelledAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  currency: string;
  deletedAt: Timestamp | null;
  exchangeRate: Numeric | null;
  expiredAt: Timestamp | null;
  failedAt: Timestamp | null;
  failureReason: string | null;
  id: Generated<string>;
  notificationUrl: string | null;
  orderId: string;
  payerCountry: string | null;
  payerDocument: string | null;
  payerDocumentType: string | null;
  payerEmail: string | null;
  payerFirstName: string | null;
  payerLastName: string | null;
  paymentMethod: PaymentMethod | null;
  provider: PaymentProvider;
  providerMetadata: Generated<Json | null>;
  providerPaymentId: string;
  redirectUrl: string | null;
  refundedAt: Timestamp | null;
  status: Generated<PaymentStatus>;
  successUrl: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface PayoutDocuments {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  documentType: Generated<string>;
  fileName: string;
  id: Generated<string>;
  mimeType: string;
  originalName: string;
  payoutId: string;
  sizeBytes: number;
  storagePath: string;
  updatedAt: Generated<Timestamp>;
  uploadedAt: Generated<Timestamp>;
  uploadedBy: string;
}

export interface PayoutEvents {
  createdAt: Generated<Timestamp>;
  createdBy: string | null;
  eventData: Generated<Json | null>;
  eventType: PayoutEventType;
  fromStatus: PayoutStatus | null;
  id: Generated<string>;
  ipAddress: string | null;
  payoutId: string;
  toStatus: PayoutStatus | null;
  userAgent: string | null;
}

export interface PayoutMethods {
  accountHolderName: string;
  accountHolderSurname: string;
  createdAt: Generated<Timestamp>;
  currency: EventTicketCurrency;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  isDefault: Generated<boolean>;
  metadata: Generated<Json | null>;
  payoutType: PayoutType;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface Payouts {
  amount: Numeric;
  completedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  currency: EventTicketCurrency;
  deletedAt: Timestamp | null;
  failedAt: Timestamp | null;
  failureReason: string | null;
  id: Generated<string>;
  idempotencyKeyHash: string | null;
  metadata: Generated<Json | null>;
  notes: string | null;
  payoutMethodId: string;
  payoutProvider: Generated<PayoutProvider>;
  processedAt: Timestamp | null;
  processedBy: string | null;
  processingFee: Numeric | null;
  requestedAt: Generated<Timestamp>;
  sellerEventProducerId: string | null;
  sellerUserId: string | null;
  sourceAmount: Numeric | null;
  sourceCurrency: EventTicketCurrency | null;
  status: Generated<PayoutStatus>;
  transactionReference: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface ProcessorSettlementItems {
  amount: Numeric;
  createdAt: Generated<Timestamp>;
  currency: string;
  description: string | null;
  exchangeRate: Numeric | null;
  fees: Numeric | null;
  id: string;
  metadata: Json | null;
  netAmount: Numeric;
  operationId: string;
  paymentId: string | null;
  payoutId: string | null;
  settlementId: string;
  updatedAt: Generated<Timestamp>;
}

export interface ProcessorSettlements {
  createdAt: Generated<Timestamp>;
  currency: string;
  id: string;
  metadata: Json | null;
  paymentProvider: Generated<PaymentProvider>;
  settlementDate: Timestamp;
  settlementId: string;
  status: string;
  totalAmount: Numeric;
  updatedAt: Generated<Timestamp>;
}

export interface PushSubscriptions {
  auth: string;
  createdAt: Generated<Timestamp>;
  endpoint: string;
  id: Generated<string>;
  p256dh: string;
  updatedAt: Generated<Timestamp>;
  userAgent: string | null;
  userId: string;
}

export interface RateLimit {
  count: Generated<number>;
  key: string;
  resetTime: Timestamp;
}

export interface SellerEarnings {
  createdAt: Generated<Timestamp>;
  currency: EventTicketCurrency;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  listingTicketId: string;
  payoutId: string | null;
  retainedReason: SellerEarningsRetainedReason | null;
  sellerAmount: Numeric;
  sellerEventProducerId: string | null;
  sellerUserId: string | null;
  status: Generated<SellerEarningsStatus>;
  updatedAt: Generated<Timestamp>;
}

export interface TicketCodes {
  createdAt: Generated<Timestamp>;
  generation: Generated<number>;
  id: Generated<string>;
  listingTicketId: string;
  secret: Buffer;
  updatedAt: Generated<Timestamp>;
  windowSeconds: Generated<number>;
}

export interface TicketDocuments {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  documentType: Generated<string>;
  fileName: string;
  id: Generated<string>;
  isPrimary: Generated<boolean>;
  mimeType: string;
  originalName: string;
  sizeBytes: number;
  status: Generated<string>;
  storagePath: string;
  ticketId: string;
  updatedAt: Generated<Timestamp>;
  uploadedAt: Generated<Timestamp>;
  verifiedAt: Timestamp | null;
  verifiedBy: string | null;
  version: Generated<number>;
}

export interface TicketOwnershipTransfers {
  createdAt: Generated<Timestamp>;
  fromOrderId: string | null;
  fromUserId: string | null;
  id: Generated<string>;
  listingTicketId: string;
  toOrderId: string | null;
  toUserId: string | null;
  transferType: TicketOwnershipTransferType;
}

export interface TicketReportActions {
  actionType: TicketReportActionType;
  comment: string | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  metadata: Json | null;
  performedByAdmin: Generated<boolean>;
  performedByUserId: string;
  ticketReportId: string;
}

export interface TicketReportAttachments {
  createdAt: Generated<Timestamp>;
  fileName: string;
  id: Generated<string>;
  mimeType: string;
  originalName: string;
  sizeBytes: number;
  storagePath: string;
  ticketReportActionId: string | null;
  ticketReportId: string;
  uploadedByUserId: string;
}

export interface TicketReportRefunds {
  createdAt: Generated<Timestamp>;
  currency: EventTicketCurrency | null;
  id: Generated<string>;
  orderTicketReservationId: string;
  processedAt: Timestamp | null;
  refundAmount: Numeric | null;
  refundStatus: Generated<TicketReportRefundStatus>;
  ticketReportId: string;
  updatedAt: Generated<Timestamp>;
}

export interface TicketReports {
  caseType: TicketReportCaseType;
  closedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  description: string | null;
  entityId: string;
  entityType: TicketReportEntityType;
  id: Generated<string>;
  reportedByUserId: string | null;
  source: Generated<TicketReportSource>;
  status: Generated<TicketReportStatus>;
  updatedAt: Generated<Timestamp>;
}

export interface Users {
  clerkId: string;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  documentCountry: string | null;
  documentImagePath: string | null;
  documentNumber: string | null;
  documentType: DocumentTypeEnum | null;
  documentVerified: Generated<boolean | null>;
  documentVerifiedAt: Timestamp | null;
  email: string;
  firstName: string | null;
  id: Generated<string>;
  imageUrl: string | null;
  lastActiveAt: Timestamp | null;
  lastName: string | null;
  manualReviewReason: string | null;
  metadata: Json | null;
  phoneNumber: string | null;
  role: Generated<UserRole>;
  selfieImagePath: string | null;
  updatedAt: Generated<Timestamp>;
  verificationAttempts: Generated<number | null>;
  verificationConfidenceScores: Json | null;
  verificationMetadata: Json | null;
  verificationSessionCreatedAt: Timestamp | null;
  verificationSessionId: string | null;
  verificationStatus: Generated<VerificationStatusEnum | null>;
  whatsappOptedIn: Generated<boolean>;
  whatsappPromptDismissed: Generated<boolean>;
}

export interface VerificationAuditLogs {
  action: string;
  confidenceScores: Json | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  metadata: Json | null;
  newStatus: string | null;
  previousStatus: string | null;
  userId: string;
}

export interface DB {
  eventImages: EventImages;
  eventProducerMembers: EventProducerMembers;
  eventProducers: EventProducers;
  events: Events;
  eventTicketWaveConfigs: EventTicketWaveConfigs;
  eventTicketWaves: EventTicketWaves;
  eventVenues: EventVenues;
  eventViewsDaily: EventViewsDaily;
  impersonationLogs: ImpersonationLogs;
  invoices: Invoices;
  jobs: Jobs;
  listings: Listings;
  listingTickets: ListingTickets;
  notificationBatches: NotificationBatches;
  notificationBatchItems: NotificationBatchItems;
  notifications: Notifications;
  orderItems: OrderItems;
  orders: Orders;
  orderTicketReservations: OrderTicketReservations;
  otpVerifications: OtpVerifications;
  paymentEvents: PaymentEvents;
  payments: Payments;
  payoutDocuments: PayoutDocuments;
  payoutEvents: PayoutEvents;
  payoutMethods: PayoutMethods;
  payouts: Payouts;
  processorSettlementItems: ProcessorSettlementItems;
  processorSettlements: ProcessorSettlements;
  pushSubscriptions: PushSubscriptions;
  rateLimit: RateLimit;
  sellerEarnings: SellerEarnings;
  ticketCodes: TicketCodes;
  ticketDocuments: TicketDocuments;
  ticketOwnershipTransfers: TicketOwnershipTransfers;
  ticketReportActions: TicketReportActions;
  ticketReportAttachments: TicketReportAttachments;
  ticketReportRefunds: TicketReportRefunds;
  ticketReports: TicketReports;
  users: Users;
  verificationAuditLogs: VerificationAuditLogs;
}
