/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type ArrayType<T> = ArrayTypeImpl<T> extends (infer U)[]
  ? U[]
  : ArrayTypeImpl<T>;

export type ArrayTypeImpl<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S[], I[], U[]>
  : T[];

export type EventImageType = "flyer" | "hero";

export type EventTicketCurrency = "USD" | "UYU";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type NotificationChannel = "email" | "in_app" | "sms";

export type NotificationStatus = "failed" | "pending" | "seen" | "sent";

export type NotificationType = "document_reminder" | "document_uploaded" | "order_confirmed" | "order_expired" | "payment_failed" | "payment_succeeded" | "ticket_sold_buyer" | "ticket_sold_seller";

export type Numeric = ColumnType<string, number | string, number | string>;

export type OrderStatus = "cancelled" | "confirmed" | "expired" | "pending";

export type PaymentEventType = "chargeback_received" | "dispute_opened" | "dispute_resolved" | "fraud_check_failed" | "manual_review_required" | "payment_created" | "refund_completed" | "refund_initiated" | "status_change" | "webhook_received";

export type PaymentMethod = "bank_transfer" | "cash" | "credit_card" | "debit_card" | "other" | "pix" | "voucher";

export type PaymentProvider = "dlocal" | "mercadopago" | "paypal" | "stripe";

export type PaymentStatus = "cancelled" | "expired" | "failed" | "paid" | "partially_refunded" | "pending" | "processing" | "refunded";

export type PayoutEventType = "admin_processed" | "cancelled" | "payout_requested" | "status_change" | "transfer_completed" | "transfer_failed" | "transfer_initiated";

export type PayoutStatus = "cancelled" | "completed" | "failed" | "pending" | "processing";

export type PayoutType = "paypal" | "uruguayan_bank";

export type QrAvailabilityTiming = "12h" | "24h" | "48h" | "6h" | "72h";

export type SellerEarningsStatus = "available" | "paid_out" | "pending" | "retained";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface EventImages {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  displayOrder: Generated<number>;
  eventId: string;
  id: Generated<string>;
  imageType: EventImageType;
  url: string;
}

export interface Events {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  description: string | null;
  eventEndDate: Timestamp;
  eventStartDate: Timestamp;
  externalId: string;
  externalUrl: string;
  id: Generated<string>;
  lastScrapedAt: Generated<Timestamp>;
  metadata: Json | null;
  name: string;
  platform: string;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
  venueAddress: string;
  venueName: string | null;
}

export interface EventTicketWaves {
  createdAt: Generated<Timestamp>;
  currency: EventTicketCurrency;
  deletedAt: Timestamp | null;
  description: string | null;
  eventId: string;
  externalId: string;
  faceValue: Numeric;
  id: Generated<string>;
  isAvailable: Generated<boolean>;
  isSoldOut: Generated<boolean>;
  lastScrapedAt: Generated<Timestamp>;
  metadata: Json | null;
  name: string;
  qrAvailabilityTiming: QrAvailabilityTiming | null;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface Listings {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  publisherUserId: string;
  soldAt: Timestamp | null;
  ticketWaveId: string;
  updatedAt: Generated<Timestamp>;
}

export interface ListingTickets {
  cancelledAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  listingId: string;
  price: Numeric;
  soldAt: Timestamp | null;
  ticketNumber: number;
  updatedAt: Generated<Timestamp>;
}

export interface Notifications {
  actions: Json | null;
  channels: ArrayType<NotificationChannel>;
  channelStatus: Generated<Json | null>;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  metadata: Json | null;
  retryCount: Generated<number>;
  seenAt: Timestamp | null;
  status: Generated<NotificationStatus>;
  type: NotificationType;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface OrderItems {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  orderId: string;
  pricePerTicket: Numeric;
  quantity: number;
  subtotal: Numeric;
  ticketWaveId: string;
  updatedAt: Generated<Timestamp>;
}

export interface Orders {
  cancelledAt: Timestamp | null;
  confirmedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  currency: EventTicketCurrency;
  deletedAt: Timestamp | null;
  eventId: string;
  id: Generated<string>;
  platformCommission: Numeric;
  reservationExpiresAt: Timestamp;
  status: Generated<OrderStatus>;
  subtotalAmount: Numeric;
  totalAmount: Numeric;
  updatedAt: Generated<Timestamp>;
  userId: string;
  vatOnCommission: Numeric;
}

export interface OrderTicketReservations {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  listingTicketId: string;
  orderId: string;
  reservedAt: Generated<Timestamp>;
  reservedUntil: Timestamp;
  updatedAt: Generated<Timestamp>;
}

export interface PaymentEvents {
  createdAt: Generated<Timestamp>;
  eventData: Generated<Json | null>;
  eventType: PaymentEventType;
  fromStatus: PaymentStatus | null;
  id: Generated<string>;
  ipAddress: string | null;
  paymentId: string;
  toStatus: PaymentStatus | null;
  userAgent: string | null;
}

export interface Payments {
  amount: Numeric;
  approvedAt: Timestamp | null;
  backUrl: string | null;
  balanceAmount: Numeric | null;
  balanceCurrency: string | null;
  balanceFee: Numeric | null;
  cancelledAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  currency: string;
  deletedAt: Timestamp | null;
  expiredAt: Timestamp | null;
  failedAt: Timestamp | null;
  failureReason: string | null;
  id: Generated<string>;
  notificationUrl: string | null;
  orderId: string;
  payerCountry: string | null;
  payerDocument: string | null;
  payerDocumentType: string | null;
  payerEmail: string | null;
  payerFirstName: string | null;
  payerLastName: string | null;
  paymentMethod: PaymentMethod | null;
  provider: PaymentProvider;
  providerMetadata: Generated<Json | null>;
  providerPaymentId: string;
  redirectUrl: string | null;
  refundedAt: Timestamp | null;
  status: Generated<PaymentStatus>;
  successUrl: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface PayoutEvents {
  createdAt: Generated<Timestamp>;
  createdBy: string | null;
  eventData: Generated<Json | null>;
  eventType: PayoutEventType;
  fromStatus: PayoutStatus | null;
  id: Generated<string>;
  ipAddress: string | null;
  payoutId: string;
  toStatus: PayoutStatus | null;
  userAgent: string | null;
}

export interface PayoutMethods {
  accountHolderName: string;
  accountHolderSurname: string;
  createdAt: Generated<Timestamp>;
  currency: EventTicketCurrency;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  isDefault: Generated<boolean>;
  metadata: Generated<Json | null>;
  payoutType: PayoutType;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface Payouts {
  amount: Numeric;
  completedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  currency: EventTicketCurrency;
  deletedAt: Timestamp | null;
  failedAt: Timestamp | null;
  failureReason: string | null;
  id: Generated<string>;
  metadata: Generated<Json | null>;
  notes: string | null;
  payoutMethodId: string;
  processedAt: Timestamp | null;
  processedBy: string | null;
  processingFee: Numeric | null;
  requestedAt: Generated<Timestamp>;
  sellerUserId: string;
  status: Generated<PayoutStatus>;
  transactionReference: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface SellerEarnings {
  createdAt: Generated<Timestamp>;
  currency: EventTicketCurrency;
  deletedAt: Timestamp | null;
  holdUntil: Timestamp;
  id: Generated<string>;
  listingTicketId: string;
  payoutId: string | null;
  sellerAmount: Numeric;
  sellerUserId: string;
  status: Generated<SellerEarningsStatus>;
  updatedAt: Generated<Timestamp>;
}

export interface TicketDocuments {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  documentType: Generated<string>;
  fileName: string;
  id: Generated<string>;
  isPrimary: Generated<boolean>;
  mimeType: string;
  originalName: string;
  sizeBytes: number;
  status: Generated<string>;
  storagePath: string;
  ticketId: string;
  updatedAt: Generated<Timestamp>;
  uploadedAt: Generated<Timestamp>;
  verifiedAt: Timestamp | null;
  verifiedBy: string | null;
  version: Generated<number>;
}

export interface Users {
  clerkId: string;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  email: string;
  firstName: string | null;
  id: Generated<string>;
  imageUrl: string | null;
  lastActiveAt: Timestamp | null;
  lastName: string | null;
  metadata: Json | null;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  eventImages: EventImages;
  events: Events;
  eventTicketWaves: EventTicketWaves;
  listings: Listings;
  listingTickets: ListingTickets;
  notifications: Notifications;
  orderItems: OrderItems;
  orders: Orders;
  orderTicketReservations: OrderTicketReservations;
  paymentEvents: PaymentEvents;
  payments: Payments;
  payoutEvents: PayoutEvents;
  payoutMethods: PayoutMethods;
  payouts: Payouts;
  sellerEarnings: SellerEarnings;
  ticketDocuments: TicketDocuments;
  users: Users;
}
