/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminosYCondicionesRouteImport } from './routes/terminos-y-condiciones'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as PreguntasFrecuentesRouteImport } from './routes/preguntas-frecuentes'
import { Route as PoliticaDePrivacidadRouteImport } from './routes/politica-de-privacidad'
import { Route as GarantiaRouteImport } from './routes/garantia'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CuentaRouteRouteImport } from './routes/cuenta/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as RegistrarseSplatRouteImport } from './routes/registrarse.$'
import { Route as IngresarSplatRouteImport } from './routes/ingresar.$'
import { Route as EventosEventIdRouteImport } from './routes/eventos/$eventId'
import { Route as EntradasPublicarRouteImport } from './routes/entradas/publicar'
import { Route as CuentaVerificarRouteImport } from './routes/cuenta/verificar'
import { Route as CuentaSubirEntradasRouteImport } from './routes/cuenta/subir-entradas'
import { Route as CuentaRetiroRouteImport } from './routes/cuenta/retiro'
import { Route as CuentaPublicacionesRouteImport } from './routes/cuenta/publicaciones'
import { Route as CuentaEstadoVerificacionRouteImport } from './routes/cuenta/estado-verificacion'
import { Route as CuentaEntradasRouteImport } from './routes/cuenta/entradas'
import { Route as CuentaConfiguracionRouteImport } from './routes/cuenta/configuracion'
import { Route as AdminVerificacionesRouteImport } from './routes/admin/verificaciones'
import { Route as AdminRetirosRouteImport } from './routes/admin/retiros'
import { Route as AdminEventosRouteImport } from './routes/admin/eventos'
import { Route as CuentaReportesIndexRouteImport } from './routes/cuenta/reportes/index'
import { Route as CheckoutOrderIdIndexRouteImport } from './routes/checkout/$orderId/index'
import { Route as AdminReportesIndexRouteImport } from './routes/admin/reportes/index'
import { Route as CuentaReportesReportIdRouteImport } from './routes/cuenta/reportes/$reportId'
import { Route as CheckoutOrderIdSuccessRouteImport } from './routes/checkout/$orderId/success'
import { Route as AdminReportesReportIdRouteImport } from './routes/admin/reportes/$reportId'

const TerminosYCondicionesRoute = TerminosYCondicionesRouteImport.update({
  id: '/terminos-y-condiciones',
  path: '/terminos-y-condiciones',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const PreguntasFrecuentesRoute = PreguntasFrecuentesRouteImport.update({
  id: '/preguntas-frecuentes',
  path: '/preguntas-frecuentes',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadRoute = PoliticaDePrivacidadRouteImport.update({
  id: '/politica-de-privacidad',
  path: '/politica-de-privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const GarantiaRoute = GarantiaRouteImport.update({
  id: '/garantia',
  path: '/garantia',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentaRouteRoute = CuentaRouteRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const RegistrarseSplatRoute = RegistrarseSplatRouteImport.update({
  id: '/registrarse/$',
  path: '/registrarse/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IngresarSplatRoute = IngresarSplatRouteImport.update({
  id: '/ingresar/$',
  path: '/ingresar/$',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosEventIdRoute = EventosEventIdRouteImport.update({
  id: '/eventos/$eventId',
  path: '/eventos/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const EntradasPublicarRoute = EntradasPublicarRouteImport.update({
  id: '/entradas/publicar',
  path: '/entradas/publicar',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentaVerificarRoute = CuentaVerificarRouteImport.update({
  id: '/verificar',
  path: '/verificar',
  getParentRoute: () => CuentaRouteRoute,
} as any)
const CuentaSubirEntradasRoute = CuentaSubirEntradasRouteImport.update({
  id: '/subir-entradas',
  path: '/subir-entradas',
  getParentRoute: () => CuentaRouteRoute,
} as any)
const CuentaRetiroRoute = CuentaRetiroRouteImport.update({
  id: '/retiro',
  path: '/retiro',
  getParentRoute: () => CuentaRouteRoute,
} as any)
const CuentaPublicacionesRoute = CuentaPublicacionesRouteImport.update({
  id: '/publicaciones',
  path: '/publicaciones',
  getParentRoute: () => CuentaRouteRoute,
} as any)
const CuentaEstadoVerificacionRoute =
  CuentaEstadoVerificacionRouteImport.update({
    id: '/estado-verificacion',
    path: '/estado-verificacion',
    getParentRoute: () => CuentaRouteRoute,
  } as any)
const CuentaEntradasRoute = CuentaEntradasRouteImport.update({
  id: '/entradas',
  path: '/entradas',
  getParentRoute: () => CuentaRouteRoute,
} as any)
const CuentaConfiguracionRoute = CuentaConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => CuentaRouteRoute,
} as any)
const AdminVerificacionesRoute = AdminVerificacionesRouteImport.update({
  id: '/verificaciones',
  path: '/verificaciones',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRetirosRoute = AdminRetirosRouteImport.update({
  id: '/retiros',
  path: '/retiros',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEventosRoute = AdminEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CuentaReportesIndexRoute = CuentaReportesIndexRouteImport.update({
  id: '/reportes/',
  path: '/reportes/',
  getParentRoute: () => CuentaRouteRoute,
} as any)
const CheckoutOrderIdIndexRoute = CheckoutOrderIdIndexRouteImport.update({
  id: '/checkout/$orderId/',
  path: '/checkout/$orderId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportesIndexRoute = AdminReportesIndexRouteImport.update({
  id: '/reportes/',
  path: '/reportes/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CuentaReportesReportIdRoute = CuentaReportesReportIdRouteImport.update({
  id: '/reportes/$reportId',
  path: '/reportes/$reportId',
  getParentRoute: () => CuentaRouteRoute,
} as any)
const CheckoutOrderIdSuccessRoute = CheckoutOrderIdSuccessRouteImport.update({
  id: '/checkout/$orderId/success',
  path: '/checkout/$orderId/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportesReportIdRoute = AdminReportesReportIdRouteImport.update({
  id: '/reportes/$reportId',
  path: '/reportes/$reportId',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/cuenta': typeof CuentaRouteRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/garantia': typeof GarantiaRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/sitemap': typeof SitemapRoute
  '/terminos-y-condiciones': typeof TerminosYCondicionesRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/retiros': typeof AdminRetirosRoute
  '/admin/verificaciones': typeof AdminVerificacionesRoute
  '/cuenta/configuracion': typeof CuentaConfiguracionRoute
  '/cuenta/entradas': typeof CuentaEntradasRoute
  '/cuenta/estado-verificacion': typeof CuentaEstadoVerificacionRoute
  '/cuenta/publicaciones': typeof CuentaPublicacionesRoute
  '/cuenta/retiro': typeof CuentaRetiroRoute
  '/cuenta/subir-entradas': typeof CuentaSubirEntradasRoute
  '/cuenta/verificar': typeof CuentaVerificarRoute
  '/entradas/publicar': typeof EntradasPublicarRoute
  '/eventos/$eventId': typeof EventosEventIdRoute
  '/ingresar/$': typeof IngresarSplatRoute
  '/registrarse/$': typeof RegistrarseSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/reportes/$reportId': typeof AdminReportesReportIdRoute
  '/checkout/$orderId/success': typeof CheckoutOrderIdSuccessRoute
  '/cuenta/reportes/$reportId': typeof CuentaReportesReportIdRoute
  '/admin/reportes/': typeof AdminReportesIndexRoute
  '/checkout/$orderId/': typeof CheckoutOrderIdIndexRoute
  '/cuenta/reportes/': typeof CuentaReportesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cuenta': typeof CuentaRouteRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/garantia': typeof GarantiaRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/sitemap': typeof SitemapRoute
  '/terminos-y-condiciones': typeof TerminosYCondicionesRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/retiros': typeof AdminRetirosRoute
  '/admin/verificaciones': typeof AdminVerificacionesRoute
  '/cuenta/configuracion': typeof CuentaConfiguracionRoute
  '/cuenta/entradas': typeof CuentaEntradasRoute
  '/cuenta/estado-verificacion': typeof CuentaEstadoVerificacionRoute
  '/cuenta/publicaciones': typeof CuentaPublicacionesRoute
  '/cuenta/retiro': typeof CuentaRetiroRoute
  '/cuenta/subir-entradas': typeof CuentaSubirEntradasRoute
  '/cuenta/verificar': typeof CuentaVerificarRoute
  '/entradas/publicar': typeof EntradasPublicarRoute
  '/eventos/$eventId': typeof EventosEventIdRoute
  '/ingresar/$': typeof IngresarSplatRoute
  '/registrarse/$': typeof RegistrarseSplatRoute
  '/admin': typeof AdminIndexRoute
  '/admin/reportes/$reportId': typeof AdminReportesReportIdRoute
  '/checkout/$orderId/success': typeof CheckoutOrderIdSuccessRoute
  '/cuenta/reportes/$reportId': typeof CuentaReportesReportIdRoute
  '/admin/reportes': typeof AdminReportesIndexRoute
  '/checkout/$orderId': typeof CheckoutOrderIdIndexRoute
  '/cuenta/reportes': typeof CuentaReportesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/cuenta': typeof CuentaRouteRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/garantia': typeof GarantiaRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/sitemap': typeof SitemapRoute
  '/terminos-y-condiciones': typeof TerminosYCondicionesRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/retiros': typeof AdminRetirosRoute
  '/admin/verificaciones': typeof AdminVerificacionesRoute
  '/cuenta/configuracion': typeof CuentaConfiguracionRoute
  '/cuenta/entradas': typeof CuentaEntradasRoute
  '/cuenta/estado-verificacion': typeof CuentaEstadoVerificacionRoute
  '/cuenta/publicaciones': typeof CuentaPublicacionesRoute
  '/cuenta/retiro': typeof CuentaRetiroRoute
  '/cuenta/subir-entradas': typeof CuentaSubirEntradasRoute
  '/cuenta/verificar': typeof CuentaVerificarRoute
  '/entradas/publicar': typeof EntradasPublicarRoute
  '/eventos/$eventId': typeof EventosEventIdRoute
  '/ingresar/$': typeof IngresarSplatRoute
  '/registrarse/$': typeof RegistrarseSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/reportes/$reportId': typeof AdminReportesReportIdRoute
  '/checkout/$orderId/success': typeof CheckoutOrderIdSuccessRoute
  '/cuenta/reportes/$reportId': typeof CuentaReportesReportIdRoute
  '/admin/reportes/': typeof AdminReportesIndexRoute
  '/checkout/$orderId/': typeof CheckoutOrderIdIndexRoute
  '/cuenta/reportes/': typeof CuentaReportesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cuenta'
    | '/contacto'
    | '/garantia'
    | '/politica-de-privacidad'
    | '/preguntas-frecuentes'
    | '/sitemap'
    | '/terminos-y-condiciones'
    | '/admin/eventos'
    | '/admin/retiros'
    | '/admin/verificaciones'
    | '/cuenta/configuracion'
    | '/cuenta/entradas'
    | '/cuenta/estado-verificacion'
    | '/cuenta/publicaciones'
    | '/cuenta/retiro'
    | '/cuenta/subir-entradas'
    | '/cuenta/verificar'
    | '/entradas/publicar'
    | '/eventos/$eventId'
    | '/ingresar/$'
    | '/registrarse/$'
    | '/admin/'
    | '/admin/reportes/$reportId'
    | '/checkout/$orderId/success'
    | '/cuenta/reportes/$reportId'
    | '/admin/reportes/'
    | '/checkout/$orderId/'
    | '/cuenta/reportes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cuenta'
    | '/contacto'
    | '/garantia'
    | '/politica-de-privacidad'
    | '/preguntas-frecuentes'
    | '/sitemap'
    | '/terminos-y-condiciones'
    | '/admin/eventos'
    | '/admin/retiros'
    | '/admin/verificaciones'
    | '/cuenta/configuracion'
    | '/cuenta/entradas'
    | '/cuenta/estado-verificacion'
    | '/cuenta/publicaciones'
    | '/cuenta/retiro'
    | '/cuenta/subir-entradas'
    | '/cuenta/verificar'
    | '/entradas/publicar'
    | '/eventos/$eventId'
    | '/ingresar/$'
    | '/registrarse/$'
    | '/admin'
    | '/admin/reportes/$reportId'
    | '/checkout/$orderId/success'
    | '/cuenta/reportes/$reportId'
    | '/admin/reportes'
    | '/checkout/$orderId'
    | '/cuenta/reportes'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cuenta'
    | '/contacto'
    | '/garantia'
    | '/politica-de-privacidad'
    | '/preguntas-frecuentes'
    | '/sitemap'
    | '/terminos-y-condiciones'
    | '/admin/eventos'
    | '/admin/retiros'
    | '/admin/verificaciones'
    | '/cuenta/configuracion'
    | '/cuenta/entradas'
    | '/cuenta/estado-verificacion'
    | '/cuenta/publicaciones'
    | '/cuenta/retiro'
    | '/cuenta/subir-entradas'
    | '/cuenta/verificar'
    | '/entradas/publicar'
    | '/eventos/$eventId'
    | '/ingresar/$'
    | '/registrarse/$'
    | '/admin/'
    | '/admin/reportes/$reportId'
    | '/checkout/$orderId/success'
    | '/cuenta/reportes/$reportId'
    | '/admin/reportes/'
    | '/checkout/$orderId/'
    | '/cuenta/reportes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  CuentaRouteRoute: typeof CuentaRouteRouteWithChildren
  ContactoRoute: typeof ContactoRoute
  GarantiaRoute: typeof GarantiaRoute
  PoliticaDePrivacidadRoute: typeof PoliticaDePrivacidadRoute
  PreguntasFrecuentesRoute: typeof PreguntasFrecuentesRoute
  SitemapRoute: typeof SitemapRoute
  TerminosYCondicionesRoute: typeof TerminosYCondicionesRoute
  EntradasPublicarRoute: typeof EntradasPublicarRoute
  EventosEventIdRoute: typeof EventosEventIdRoute
  IngresarSplatRoute: typeof IngresarSplatRoute
  RegistrarseSplatRoute: typeof RegistrarseSplatRoute
  CheckoutOrderIdSuccessRoute: typeof CheckoutOrderIdSuccessRoute
  CheckoutOrderIdIndexRoute: typeof CheckoutOrderIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminos-y-condiciones': {
      id: '/terminos-y-condiciones'
      path: '/terminos-y-condiciones'
      fullPath: '/terminos-y-condiciones'
      preLoaderRoute: typeof TerminosYCondicionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preguntas-frecuentes': {
      id: '/preguntas-frecuentes'
      path: '/preguntas-frecuentes'
      fullPath: '/preguntas-frecuentes'
      preLoaderRoute: typeof PreguntasFrecuentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidad': {
      id: '/politica-de-privacidad'
      path: '/politica-de-privacidad'
      fullPath: '/politica-de-privacidad'
      preLoaderRoute: typeof PoliticaDePrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garantia': {
      id: '/garantia'
      path: '/garantia'
      fullPath: '/garantia'
      preLoaderRoute: typeof GarantiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuenta': {
      id: '/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof CuentaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/registrarse/$': {
      id: '/registrarse/$'
      path: '/registrarse/$'
      fullPath: '/registrarse/$'
      preLoaderRoute: typeof RegistrarseSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingresar/$': {
      id: '/ingresar/$'
      path: '/ingresar/$'
      fullPath: '/ingresar/$'
      preLoaderRoute: typeof IngresarSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/$eventId': {
      id: '/eventos/$eventId'
      path: '/eventos/$eventId'
      fullPath: '/eventos/$eventId'
      preLoaderRoute: typeof EventosEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entradas/publicar': {
      id: '/entradas/publicar'
      path: '/entradas/publicar'
      fullPath: '/entradas/publicar'
      preLoaderRoute: typeof EntradasPublicarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuenta/verificar': {
      id: '/cuenta/verificar'
      path: '/verificar'
      fullPath: '/cuenta/verificar'
      preLoaderRoute: typeof CuentaVerificarRouteImport
      parentRoute: typeof CuentaRouteRoute
    }
    '/cuenta/subir-entradas': {
      id: '/cuenta/subir-entradas'
      path: '/subir-entradas'
      fullPath: '/cuenta/subir-entradas'
      preLoaderRoute: typeof CuentaSubirEntradasRouteImport
      parentRoute: typeof CuentaRouteRoute
    }
    '/cuenta/retiro': {
      id: '/cuenta/retiro'
      path: '/retiro'
      fullPath: '/cuenta/retiro'
      preLoaderRoute: typeof CuentaRetiroRouteImport
      parentRoute: typeof CuentaRouteRoute
    }
    '/cuenta/publicaciones': {
      id: '/cuenta/publicaciones'
      path: '/publicaciones'
      fullPath: '/cuenta/publicaciones'
      preLoaderRoute: typeof CuentaPublicacionesRouteImport
      parentRoute: typeof CuentaRouteRoute
    }
    '/cuenta/estado-verificacion': {
      id: '/cuenta/estado-verificacion'
      path: '/estado-verificacion'
      fullPath: '/cuenta/estado-verificacion'
      preLoaderRoute: typeof CuentaEstadoVerificacionRouteImport
      parentRoute: typeof CuentaRouteRoute
    }
    '/cuenta/entradas': {
      id: '/cuenta/entradas'
      path: '/entradas'
      fullPath: '/cuenta/entradas'
      preLoaderRoute: typeof CuentaEntradasRouteImport
      parentRoute: typeof CuentaRouteRoute
    }
    '/cuenta/configuracion': {
      id: '/cuenta/configuracion'
      path: '/configuracion'
      fullPath: '/cuenta/configuracion'
      preLoaderRoute: typeof CuentaConfiguracionRouteImport
      parentRoute: typeof CuentaRouteRoute
    }
    '/admin/verificaciones': {
      id: '/admin/verificaciones'
      path: '/verificaciones'
      fullPath: '/admin/verificaciones'
      preLoaderRoute: typeof AdminVerificacionesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/retiros': {
      id: '/admin/retiros'
      path: '/retiros'
      fullPath: '/admin/retiros'
      preLoaderRoute: typeof AdminRetirosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/eventos': {
      id: '/admin/eventos'
      path: '/eventos'
      fullPath: '/admin/eventos'
      preLoaderRoute: typeof AdminEventosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/cuenta/reportes/': {
      id: '/cuenta/reportes/'
      path: '/reportes'
      fullPath: '/cuenta/reportes/'
      preLoaderRoute: typeof CuentaReportesIndexRouteImport
      parentRoute: typeof CuentaRouteRoute
    }
    '/checkout/$orderId/': {
      id: '/checkout/$orderId/'
      path: '/checkout/$orderId'
      fullPath: '/checkout/$orderId/'
      preLoaderRoute: typeof CheckoutOrderIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reportes/': {
      id: '/admin/reportes/'
      path: '/reportes'
      fullPath: '/admin/reportes/'
      preLoaderRoute: typeof AdminReportesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/cuenta/reportes/$reportId': {
      id: '/cuenta/reportes/$reportId'
      path: '/reportes/$reportId'
      fullPath: '/cuenta/reportes/$reportId'
      preLoaderRoute: typeof CuentaReportesReportIdRouteImport
      parentRoute: typeof CuentaRouteRoute
    }
    '/checkout/$orderId/success': {
      id: '/checkout/$orderId/success'
      path: '/checkout/$orderId/success'
      fullPath: '/checkout/$orderId/success'
      preLoaderRoute: typeof CheckoutOrderIdSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reportes/$reportId': {
      id: '/admin/reportes/$reportId'
      path: '/reportes/$reportId'
      fullPath: '/admin/reportes/$reportId'
      preLoaderRoute: typeof AdminReportesReportIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminEventosRoute: typeof AdminEventosRoute
  AdminRetirosRoute: typeof AdminRetirosRoute
  AdminVerificacionesRoute: typeof AdminVerificacionesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminReportesReportIdRoute: typeof AdminReportesReportIdRoute
  AdminReportesIndexRoute: typeof AdminReportesIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminEventosRoute: AdminEventosRoute,
  AdminRetirosRoute: AdminRetirosRoute,
  AdminVerificacionesRoute: AdminVerificacionesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminReportesReportIdRoute: AdminReportesReportIdRoute,
  AdminReportesIndexRoute: AdminReportesIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface CuentaRouteRouteChildren {
  CuentaConfiguracionRoute: typeof CuentaConfiguracionRoute
  CuentaEntradasRoute: typeof CuentaEntradasRoute
  CuentaEstadoVerificacionRoute: typeof CuentaEstadoVerificacionRoute
  CuentaPublicacionesRoute: typeof CuentaPublicacionesRoute
  CuentaRetiroRoute: typeof CuentaRetiroRoute
  CuentaSubirEntradasRoute: typeof CuentaSubirEntradasRoute
  CuentaVerificarRoute: typeof CuentaVerificarRoute
  CuentaReportesReportIdRoute: typeof CuentaReportesReportIdRoute
  CuentaReportesIndexRoute: typeof CuentaReportesIndexRoute
}

const CuentaRouteRouteChildren: CuentaRouteRouteChildren = {
  CuentaConfiguracionRoute: CuentaConfiguracionRoute,
  CuentaEntradasRoute: CuentaEntradasRoute,
  CuentaEstadoVerificacionRoute: CuentaEstadoVerificacionRoute,
  CuentaPublicacionesRoute: CuentaPublicacionesRoute,
  CuentaRetiroRoute: CuentaRetiroRoute,
  CuentaSubirEntradasRoute: CuentaSubirEntradasRoute,
  CuentaVerificarRoute: CuentaVerificarRoute,
  CuentaReportesReportIdRoute: CuentaReportesReportIdRoute,
  CuentaReportesIndexRoute: CuentaReportesIndexRoute,
}

const CuentaRouteRouteWithChildren = CuentaRouteRoute._addFileChildren(
  CuentaRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  CuentaRouteRoute: CuentaRouteRouteWithChildren,
  ContactoRoute: ContactoRoute,
  GarantiaRoute: GarantiaRoute,
  PoliticaDePrivacidadRoute: PoliticaDePrivacidadRoute,
  PreguntasFrecuentesRoute: PreguntasFrecuentesRoute,
  SitemapRoute: SitemapRoute,
  TerminosYCondicionesRoute: TerminosYCondicionesRoute,
  EntradasPublicarRoute: EntradasPublicarRoute,
  EventosEventIdRoute: EventosEventIdRoute,
  IngresarSplatRoute: IngresarSplatRoute,
  RegistrarseSplatRoute: RegistrarseSplatRoute,
  CheckoutOrderIdSuccessRoute: CheckoutOrderIdSuccessRoute,
  CheckoutOrderIdIndexRoute: CheckoutOrderIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
