/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminosYCondicionesRouteImport } from './routes/terminos-y-condiciones'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as PreguntasFrecuentesRouteImport } from './routes/preguntas-frecuentes'
import { Route as PoliticaDePrivacidadRouteImport } from './routes/politica-de-privacidad'
import { Route as GarantiaRouteImport } from './routes/garantia'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CuentaRouteRouteImport } from './routes/cuenta/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as RegistrarseSplatRouteImport } from './routes/registrarse.$'
import { Route as IngresarSplatRouteImport } from './routes/ingresar.$'
import { Route as EventosHoyRouteImport } from './routes/eventos/hoy'
import { Route as EventosEsteFinDeSemanaRouteImport } from './routes/eventos/este-fin-de-semana'
import { Route as EventosSlugRouteImport } from './routes/eventos/$slug'
import { Route as EntradasPublicarRouteImport } from './routes/entradas/publicar'
import { Route as CuentaVerificarRouteImport } from './routes/cuenta/verificar'
import { Route as CuentaSubirEntradasRouteImport } from './routes/cuenta/subir-entradas'
import { Route as CuentaEstadoVerificacionRouteImport } from './routes/cuenta/estado-verificacion'
import { Route as CuentaEntradasRouteImport } from './routes/cuenta/entradas'
import { Route as CuentaConfiguracionRouteImport } from './routes/cuenta/configuracion'
import { Route as AdminVerificacionesRouteImport } from './routes/admin/verificaciones'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as CuentaRetiroRouteRouteImport } from './routes/cuenta/retiro/route'
import { Route as AdminRetirosRouteRouteImport } from './routes/admin/retiros/route'
import { Route as AdminFinanzasRouteRouteImport } from './routes/admin/finanzas/route'
import { Route as AdminEventosRouteRouteImport } from './routes/admin/eventos/route'
import { Route as CuentaRetiroIndexRouteImport } from './routes/cuenta/retiro/index'
import { Route as CuentaReportesIndexRouteImport } from './routes/cuenta/reportes/index'
import { Route as CuentaPublicacionesIndexRouteImport } from './routes/cuenta/publicaciones/index'
import { Route as CheckoutOrderIdIndexRouteImport } from './routes/checkout/$orderId/index'
import { Route as AdminTareasProgramadasIndexRouteImport } from './routes/admin/tareas-programadas/index'
import { Route as AdminRetirosIndexRouteImport } from './routes/admin/retiros/index'
import { Route as AdminReportesIndexRouteImport } from './routes/admin/reportes/index'
import { Route as AdminFinanzasIndexRouteImport } from './routes/admin/finanzas/index'
import { Route as AdminEventosIndexRouteImport } from './routes/admin/eventos/index'
import { Route as EventosEnLocationRouteImport } from './routes/eventos/en.$location'
import { Route as CuentaRetiroPayoutIdRouteImport } from './routes/cuenta/retiro/$payoutId'
import { Route as CuentaReportesReportIdRouteImport } from './routes/cuenta/reportes/$reportId'
import { Route as CuentaPublicacionesListingIdRouteImport } from './routes/cuenta/publicaciones/$listingId'
import { Route as CheckoutOrderIdSuccessRouteImport } from './routes/checkout/$orderId/success'
import { Route as AdminRetirosPayoutIdRouteImport } from './routes/admin/retiros/$payoutId'
import { Route as AdminReportesReportIdRouteImport } from './routes/admin/reportes/$reportId'
import { Route as AdminEventosEventIdRouteImport } from './routes/admin/eventos/$eventId'
import { Route as AdminFinanzasLiquidacionesSettlementIdRouteImport } from './routes/admin/finanzas/liquidaciones/$settlementId'

const TerminosYCondicionesRoute = TerminosYCondicionesRouteImport.update({
  id: '/terminos-y-condiciones',
  path: '/terminos-y-condiciones',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const PreguntasFrecuentesRoute = PreguntasFrecuentesRouteImport.update({
  id: '/preguntas-frecuentes',
  path: '/preguntas-frecuentes',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadRoute = PoliticaDePrivacidadRouteImport.update({
  id: '/politica-de-privacidad',
  path: '/politica-de-privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const GarantiaRoute = GarantiaRouteImport.update({
  id: '/garantia',
  path: '/garantia',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentaRouteRoute = CuentaRouteRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const RegistrarseSplatRoute = RegistrarseSplatRouteImport.update({
  id: '/registrarse/$',
  path: '/registrarse/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IngresarSplatRoute = IngresarSplatRouteImport.update({
  id: '/ingresar/$',
  path: '/ingresar/$',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosHoyRoute = EventosHoyRouteImport.update({
  id: '/eventos/hoy',
  path: '/eventos/hoy',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosEsteFinDeSemanaRoute = EventosEsteFinDeSemanaRouteImport.update({
  id: '/eventos/este-fin-de-semana',
  path: '/eventos/este-fin-de-semana',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosSlugRoute = EventosSlugRouteImport.update({
  id: '/eventos/$slug',
  path: '/eventos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EntradasPublicarRoute = EntradasPublicarRouteImport.update({
  id: '/entradas/publicar',
  path: '/entradas/publicar',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentaVerificarRoute = CuentaVerificarRouteImport.update({
  id: '/verificar',
  path: '/verificar',
  getParentRoute: () => CuentaRouteRoute,
} as any)
const CuentaSubirEntradasRoute = CuentaSubirEntradasRouteImport.update({
  id: '/subir-entradas',
  path: '/subir-entradas',
  getParentRoute: () => CuentaRouteRoute,
} as any)
const CuentaEstadoVerificacionRoute =
  CuentaEstadoVerificacionRouteImport.update({
    id: '/estado-verificacion',
    path: '/estado-verificacion',
    getParentRoute: () => CuentaRouteRoute,
  } as any)
const CuentaEntradasRoute = CuentaEntradasRouteImport.update({
  id: '/entradas',
  path: '/entradas',
  getParentRoute: () => CuentaRouteRoute,
} as any)
const CuentaConfiguracionRoute = CuentaConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => CuentaRouteRoute,
} as any)
const AdminVerificacionesRoute = AdminVerificacionesRouteImport.update({
  id: '/verificaciones',
  path: '/verificaciones',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CuentaRetiroRouteRoute = CuentaRetiroRouteRouteImport.update({
  id: '/retiro',
  path: '/retiro',
  getParentRoute: () => CuentaRouteRoute,
} as any)
const AdminRetirosRouteRoute = AdminRetirosRouteRouteImport.update({
  id: '/retiros',
  path: '/retiros',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFinanzasRouteRoute = AdminFinanzasRouteRouteImport.update({
  id: '/finanzas',
  path: '/finanzas',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEventosRouteRoute = AdminEventosRouteRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CuentaRetiroIndexRoute = CuentaRetiroIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CuentaRetiroRouteRoute,
} as any)
const CuentaReportesIndexRoute = CuentaReportesIndexRouteImport.update({
  id: '/reportes/',
  path: '/reportes/',
  getParentRoute: () => CuentaRouteRoute,
} as any)
const CuentaPublicacionesIndexRoute =
  CuentaPublicacionesIndexRouteImport.update({
    id: '/publicaciones/',
    path: '/publicaciones/',
    getParentRoute: () => CuentaRouteRoute,
  } as any)
const CheckoutOrderIdIndexRoute = CheckoutOrderIdIndexRouteImport.update({
  id: '/checkout/$orderId/',
  path: '/checkout/$orderId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTareasProgramadasIndexRoute =
  AdminTareasProgramadasIndexRouteImport.update({
    id: '/tareas-programadas/',
    path: '/tareas-programadas/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminRetirosIndexRoute = AdminRetirosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRetirosRouteRoute,
} as any)
const AdminReportesIndexRoute = AdminReportesIndexRouteImport.update({
  id: '/reportes/',
  path: '/reportes/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFinanzasIndexRoute = AdminFinanzasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminFinanzasRouteRoute,
} as any)
const AdminEventosIndexRoute = AdminEventosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminEventosRouteRoute,
} as any)
const EventosEnLocationRoute = EventosEnLocationRouteImport.update({
  id: '/eventos/en/$location',
  path: '/eventos/en/$location',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentaRetiroPayoutIdRoute = CuentaRetiroPayoutIdRouteImport.update({
  id: '/$payoutId',
  path: '/$payoutId',
  getParentRoute: () => CuentaRetiroRouteRoute,
} as any)
const CuentaReportesReportIdRoute = CuentaReportesReportIdRouteImport.update({
  id: '/reportes/$reportId',
  path: '/reportes/$reportId',
  getParentRoute: () => CuentaRouteRoute,
} as any)
const CuentaPublicacionesListingIdRoute =
  CuentaPublicacionesListingIdRouteImport.update({
    id: '/publicaciones/$listingId',
    path: '/publicaciones/$listingId',
    getParentRoute: () => CuentaRouteRoute,
  } as any)
const CheckoutOrderIdSuccessRoute = CheckoutOrderIdSuccessRouteImport.update({
  id: '/checkout/$orderId/success',
  path: '/checkout/$orderId/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRetirosPayoutIdRoute = AdminRetirosPayoutIdRouteImport.update({
  id: '/$payoutId',
  path: '/$payoutId',
  getParentRoute: () => AdminRetirosRouteRoute,
} as any)
const AdminReportesReportIdRoute = AdminReportesReportIdRouteImport.update({
  id: '/reportes/$reportId',
  path: '/reportes/$reportId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEventosEventIdRoute = AdminEventosEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => AdminEventosRouteRoute,
} as any)
const AdminFinanzasLiquidacionesSettlementIdRoute =
  AdminFinanzasLiquidacionesSettlementIdRouteImport.update({
    id: '/liquidaciones/$settlementId',
    path: '/liquidaciones/$settlementId',
    getParentRoute: () => AdminFinanzasRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/cuenta': typeof CuentaRouteRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/garantia': typeof GarantiaRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/sitemap': typeof SitemapRoute
  '/terminos-y-condiciones': typeof TerminosYCondicionesRoute
  '/admin/eventos': typeof AdminEventosRouteRouteWithChildren
  '/admin/finanzas': typeof AdminFinanzasRouteRouteWithChildren
  '/admin/retiros': typeof AdminRetirosRouteRouteWithChildren
  '/cuenta/retiro': typeof CuentaRetiroRouteRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/verificaciones': typeof AdminVerificacionesRoute
  '/cuenta/configuracion': typeof CuentaConfiguracionRoute
  '/cuenta/entradas': typeof CuentaEntradasRoute
  '/cuenta/estado-verificacion': typeof CuentaEstadoVerificacionRoute
  '/cuenta/subir-entradas': typeof CuentaSubirEntradasRoute
  '/cuenta/verificar': typeof CuentaVerificarRoute
  '/entradas/publicar': typeof EntradasPublicarRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/eventos/este-fin-de-semana': typeof EventosEsteFinDeSemanaRoute
  '/eventos/hoy': typeof EventosHoyRoute
  '/ingresar/$': typeof IngresarSplatRoute
  '/registrarse/$': typeof RegistrarseSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/eventos/$eventId': typeof AdminEventosEventIdRoute
  '/admin/reportes/$reportId': typeof AdminReportesReportIdRoute
  '/admin/retiros/$payoutId': typeof AdminRetirosPayoutIdRoute
  '/checkout/$orderId/success': typeof CheckoutOrderIdSuccessRoute
  '/cuenta/publicaciones/$listingId': typeof CuentaPublicacionesListingIdRoute
  '/cuenta/reportes/$reportId': typeof CuentaReportesReportIdRoute
  '/cuenta/retiro/$payoutId': typeof CuentaRetiroPayoutIdRoute
  '/eventos/en/$location': typeof EventosEnLocationRoute
  '/admin/eventos/': typeof AdminEventosIndexRoute
  '/admin/finanzas/': typeof AdminFinanzasIndexRoute
  '/admin/reportes/': typeof AdminReportesIndexRoute
  '/admin/retiros/': typeof AdminRetirosIndexRoute
  '/admin/tareas-programadas/': typeof AdminTareasProgramadasIndexRoute
  '/checkout/$orderId/': typeof CheckoutOrderIdIndexRoute
  '/cuenta/publicaciones/': typeof CuentaPublicacionesIndexRoute
  '/cuenta/reportes/': typeof CuentaReportesIndexRoute
  '/cuenta/retiro/': typeof CuentaRetiroIndexRoute
  '/admin/finanzas/liquidaciones/$settlementId': typeof AdminFinanzasLiquidacionesSettlementIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cuenta': typeof CuentaRouteRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/garantia': typeof GarantiaRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/sitemap': typeof SitemapRoute
  '/terminos-y-condiciones': typeof TerminosYCondicionesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/verificaciones': typeof AdminVerificacionesRoute
  '/cuenta/configuracion': typeof CuentaConfiguracionRoute
  '/cuenta/entradas': typeof CuentaEntradasRoute
  '/cuenta/estado-verificacion': typeof CuentaEstadoVerificacionRoute
  '/cuenta/subir-entradas': typeof CuentaSubirEntradasRoute
  '/cuenta/verificar': typeof CuentaVerificarRoute
  '/entradas/publicar': typeof EntradasPublicarRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/eventos/este-fin-de-semana': typeof EventosEsteFinDeSemanaRoute
  '/eventos/hoy': typeof EventosHoyRoute
  '/ingresar/$': typeof IngresarSplatRoute
  '/registrarse/$': typeof RegistrarseSplatRoute
  '/admin': typeof AdminIndexRoute
  '/admin/eventos/$eventId': typeof AdminEventosEventIdRoute
  '/admin/reportes/$reportId': typeof AdminReportesReportIdRoute
  '/admin/retiros/$payoutId': typeof AdminRetirosPayoutIdRoute
  '/checkout/$orderId/success': typeof CheckoutOrderIdSuccessRoute
  '/cuenta/publicaciones/$listingId': typeof CuentaPublicacionesListingIdRoute
  '/cuenta/reportes/$reportId': typeof CuentaReportesReportIdRoute
  '/cuenta/retiro/$payoutId': typeof CuentaRetiroPayoutIdRoute
  '/eventos/en/$location': typeof EventosEnLocationRoute
  '/admin/eventos': typeof AdminEventosIndexRoute
  '/admin/finanzas': typeof AdminFinanzasIndexRoute
  '/admin/reportes': typeof AdminReportesIndexRoute
  '/admin/retiros': typeof AdminRetirosIndexRoute
  '/admin/tareas-programadas': typeof AdminTareasProgramadasIndexRoute
  '/checkout/$orderId': typeof CheckoutOrderIdIndexRoute
  '/cuenta/publicaciones': typeof CuentaPublicacionesIndexRoute
  '/cuenta/reportes': typeof CuentaReportesIndexRoute
  '/cuenta/retiro': typeof CuentaRetiroIndexRoute
  '/admin/finanzas/liquidaciones/$settlementId': typeof AdminFinanzasLiquidacionesSettlementIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/cuenta': typeof CuentaRouteRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/garantia': typeof GarantiaRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/sitemap': typeof SitemapRoute
  '/terminos-y-condiciones': typeof TerminosYCondicionesRoute
  '/admin/eventos': typeof AdminEventosRouteRouteWithChildren
  '/admin/finanzas': typeof AdminFinanzasRouteRouteWithChildren
  '/admin/retiros': typeof AdminRetirosRouteRouteWithChildren
  '/cuenta/retiro': typeof CuentaRetiroRouteRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/verificaciones': typeof AdminVerificacionesRoute
  '/cuenta/configuracion': typeof CuentaConfiguracionRoute
  '/cuenta/entradas': typeof CuentaEntradasRoute
  '/cuenta/estado-verificacion': typeof CuentaEstadoVerificacionRoute
  '/cuenta/subir-entradas': typeof CuentaSubirEntradasRoute
  '/cuenta/verificar': typeof CuentaVerificarRoute
  '/entradas/publicar': typeof EntradasPublicarRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/eventos/este-fin-de-semana': typeof EventosEsteFinDeSemanaRoute
  '/eventos/hoy': typeof EventosHoyRoute
  '/ingresar/$': typeof IngresarSplatRoute
  '/registrarse/$': typeof RegistrarseSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/eventos/$eventId': typeof AdminEventosEventIdRoute
  '/admin/reportes/$reportId': typeof AdminReportesReportIdRoute
  '/admin/retiros/$payoutId': typeof AdminRetirosPayoutIdRoute
  '/checkout/$orderId/success': typeof CheckoutOrderIdSuccessRoute
  '/cuenta/publicaciones/$listingId': typeof CuentaPublicacionesListingIdRoute
  '/cuenta/reportes/$reportId': typeof CuentaReportesReportIdRoute
  '/cuenta/retiro/$payoutId': typeof CuentaRetiroPayoutIdRoute
  '/eventos/en/$location': typeof EventosEnLocationRoute
  '/admin/eventos/': typeof AdminEventosIndexRoute
  '/admin/finanzas/': typeof AdminFinanzasIndexRoute
  '/admin/reportes/': typeof AdminReportesIndexRoute
  '/admin/retiros/': typeof AdminRetirosIndexRoute
  '/admin/tareas-programadas/': typeof AdminTareasProgramadasIndexRoute
  '/checkout/$orderId/': typeof CheckoutOrderIdIndexRoute
  '/cuenta/publicaciones/': typeof CuentaPublicacionesIndexRoute
  '/cuenta/reportes/': typeof CuentaReportesIndexRoute
  '/cuenta/retiro/': typeof CuentaRetiroIndexRoute
  '/admin/finanzas/liquidaciones/$settlementId': typeof AdminFinanzasLiquidacionesSettlementIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cuenta'
    | '/contacto'
    | '/garantia'
    | '/politica-de-privacidad'
    | '/preguntas-frecuentes'
    | '/sitemap'
    | '/terminos-y-condiciones'
    | '/admin/eventos'
    | '/admin/finanzas'
    | '/admin/retiros'
    | '/cuenta/retiro'
    | '/admin/dashboard'
    | '/admin/verificaciones'
    | '/cuenta/configuracion'
    | '/cuenta/entradas'
    | '/cuenta/estado-verificacion'
    | '/cuenta/subir-entradas'
    | '/cuenta/verificar'
    | '/entradas/publicar'
    | '/eventos/$slug'
    | '/eventos/este-fin-de-semana'
    | '/eventos/hoy'
    | '/ingresar/$'
    | '/registrarse/$'
    | '/admin/'
    | '/admin/eventos/$eventId'
    | '/admin/reportes/$reportId'
    | '/admin/retiros/$payoutId'
    | '/checkout/$orderId/success'
    | '/cuenta/publicaciones/$listingId'
    | '/cuenta/reportes/$reportId'
    | '/cuenta/retiro/$payoutId'
    | '/eventos/en/$location'
    | '/admin/eventos/'
    | '/admin/finanzas/'
    | '/admin/reportes/'
    | '/admin/retiros/'
    | '/admin/tareas-programadas/'
    | '/checkout/$orderId/'
    | '/cuenta/publicaciones/'
    | '/cuenta/reportes/'
    | '/cuenta/retiro/'
    | '/admin/finanzas/liquidaciones/$settlementId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cuenta'
    | '/contacto'
    | '/garantia'
    | '/politica-de-privacidad'
    | '/preguntas-frecuentes'
    | '/sitemap'
    | '/terminos-y-condiciones'
    | '/admin/dashboard'
    | '/admin/verificaciones'
    | '/cuenta/configuracion'
    | '/cuenta/entradas'
    | '/cuenta/estado-verificacion'
    | '/cuenta/subir-entradas'
    | '/cuenta/verificar'
    | '/entradas/publicar'
    | '/eventos/$slug'
    | '/eventos/este-fin-de-semana'
    | '/eventos/hoy'
    | '/ingresar/$'
    | '/registrarse/$'
    | '/admin'
    | '/admin/eventos/$eventId'
    | '/admin/reportes/$reportId'
    | '/admin/retiros/$payoutId'
    | '/checkout/$orderId/success'
    | '/cuenta/publicaciones/$listingId'
    | '/cuenta/reportes/$reportId'
    | '/cuenta/retiro/$payoutId'
    | '/eventos/en/$location'
    | '/admin/eventos'
    | '/admin/finanzas'
    | '/admin/reportes'
    | '/admin/retiros'
    | '/admin/tareas-programadas'
    | '/checkout/$orderId'
    | '/cuenta/publicaciones'
    | '/cuenta/reportes'
    | '/cuenta/retiro'
    | '/admin/finanzas/liquidaciones/$settlementId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cuenta'
    | '/contacto'
    | '/garantia'
    | '/politica-de-privacidad'
    | '/preguntas-frecuentes'
    | '/sitemap'
    | '/terminos-y-condiciones'
    | '/admin/eventos'
    | '/admin/finanzas'
    | '/admin/retiros'
    | '/cuenta/retiro'
    | '/admin/dashboard'
    | '/admin/verificaciones'
    | '/cuenta/configuracion'
    | '/cuenta/entradas'
    | '/cuenta/estado-verificacion'
    | '/cuenta/subir-entradas'
    | '/cuenta/verificar'
    | '/entradas/publicar'
    | '/eventos/$slug'
    | '/eventos/este-fin-de-semana'
    | '/eventos/hoy'
    | '/ingresar/$'
    | '/registrarse/$'
    | '/admin/'
    | '/admin/eventos/$eventId'
    | '/admin/reportes/$reportId'
    | '/admin/retiros/$payoutId'
    | '/checkout/$orderId/success'
    | '/cuenta/publicaciones/$listingId'
    | '/cuenta/reportes/$reportId'
    | '/cuenta/retiro/$payoutId'
    | '/eventos/en/$location'
    | '/admin/eventos/'
    | '/admin/finanzas/'
    | '/admin/reportes/'
    | '/admin/retiros/'
    | '/admin/tareas-programadas/'
    | '/checkout/$orderId/'
    | '/cuenta/publicaciones/'
    | '/cuenta/reportes/'
    | '/cuenta/retiro/'
    | '/admin/finanzas/liquidaciones/$settlementId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  CuentaRouteRoute: typeof CuentaRouteRouteWithChildren
  ContactoRoute: typeof ContactoRoute
  GarantiaRoute: typeof GarantiaRoute
  PoliticaDePrivacidadRoute: typeof PoliticaDePrivacidadRoute
  PreguntasFrecuentesRoute: typeof PreguntasFrecuentesRoute
  SitemapRoute: typeof SitemapRoute
  TerminosYCondicionesRoute: typeof TerminosYCondicionesRoute
  EntradasPublicarRoute: typeof EntradasPublicarRoute
  EventosSlugRoute: typeof EventosSlugRoute
  EventosEsteFinDeSemanaRoute: typeof EventosEsteFinDeSemanaRoute
  EventosHoyRoute: typeof EventosHoyRoute
  IngresarSplatRoute: typeof IngresarSplatRoute
  RegistrarseSplatRoute: typeof RegistrarseSplatRoute
  CheckoutOrderIdSuccessRoute: typeof CheckoutOrderIdSuccessRoute
  EventosEnLocationRoute: typeof EventosEnLocationRoute
  CheckoutOrderIdIndexRoute: typeof CheckoutOrderIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminos-y-condiciones': {
      id: '/terminos-y-condiciones'
      path: '/terminos-y-condiciones'
      fullPath: '/terminos-y-condiciones'
      preLoaderRoute: typeof TerminosYCondicionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preguntas-frecuentes': {
      id: '/preguntas-frecuentes'
      path: '/preguntas-frecuentes'
      fullPath: '/preguntas-frecuentes'
      preLoaderRoute: typeof PreguntasFrecuentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidad': {
      id: '/politica-de-privacidad'
      path: '/politica-de-privacidad'
      fullPath: '/politica-de-privacidad'
      preLoaderRoute: typeof PoliticaDePrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garantia': {
      id: '/garantia'
      path: '/garantia'
      fullPath: '/garantia'
      preLoaderRoute: typeof GarantiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuenta': {
      id: '/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof CuentaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/registrarse/$': {
      id: '/registrarse/$'
      path: '/registrarse/$'
      fullPath: '/registrarse/$'
      preLoaderRoute: typeof RegistrarseSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingresar/$': {
      id: '/ingresar/$'
      path: '/ingresar/$'
      fullPath: '/ingresar/$'
      preLoaderRoute: typeof IngresarSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/hoy': {
      id: '/eventos/hoy'
      path: '/eventos/hoy'
      fullPath: '/eventos/hoy'
      preLoaderRoute: typeof EventosHoyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/este-fin-de-semana': {
      id: '/eventos/este-fin-de-semana'
      path: '/eventos/este-fin-de-semana'
      fullPath: '/eventos/este-fin-de-semana'
      preLoaderRoute: typeof EventosEsteFinDeSemanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/$slug': {
      id: '/eventos/$slug'
      path: '/eventos/$slug'
      fullPath: '/eventos/$slug'
      preLoaderRoute: typeof EventosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entradas/publicar': {
      id: '/entradas/publicar'
      path: '/entradas/publicar'
      fullPath: '/entradas/publicar'
      preLoaderRoute: typeof EntradasPublicarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuenta/verificar': {
      id: '/cuenta/verificar'
      path: '/verificar'
      fullPath: '/cuenta/verificar'
      preLoaderRoute: typeof CuentaVerificarRouteImport
      parentRoute: typeof CuentaRouteRoute
    }
    '/cuenta/subir-entradas': {
      id: '/cuenta/subir-entradas'
      path: '/subir-entradas'
      fullPath: '/cuenta/subir-entradas'
      preLoaderRoute: typeof CuentaSubirEntradasRouteImport
      parentRoute: typeof CuentaRouteRoute
    }
    '/cuenta/estado-verificacion': {
      id: '/cuenta/estado-verificacion'
      path: '/estado-verificacion'
      fullPath: '/cuenta/estado-verificacion'
      preLoaderRoute: typeof CuentaEstadoVerificacionRouteImport
      parentRoute: typeof CuentaRouteRoute
    }
    '/cuenta/entradas': {
      id: '/cuenta/entradas'
      path: '/entradas'
      fullPath: '/cuenta/entradas'
      preLoaderRoute: typeof CuentaEntradasRouteImport
      parentRoute: typeof CuentaRouteRoute
    }
    '/cuenta/configuracion': {
      id: '/cuenta/configuracion'
      path: '/configuracion'
      fullPath: '/cuenta/configuracion'
      preLoaderRoute: typeof CuentaConfiguracionRouteImport
      parentRoute: typeof CuentaRouteRoute
    }
    '/admin/verificaciones': {
      id: '/admin/verificaciones'
      path: '/verificaciones'
      fullPath: '/admin/verificaciones'
      preLoaderRoute: typeof AdminVerificacionesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/cuenta/retiro': {
      id: '/cuenta/retiro'
      path: '/retiro'
      fullPath: '/cuenta/retiro'
      preLoaderRoute: typeof CuentaRetiroRouteRouteImport
      parentRoute: typeof CuentaRouteRoute
    }
    '/admin/retiros': {
      id: '/admin/retiros'
      path: '/retiros'
      fullPath: '/admin/retiros'
      preLoaderRoute: typeof AdminRetirosRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/finanzas': {
      id: '/admin/finanzas'
      path: '/finanzas'
      fullPath: '/admin/finanzas'
      preLoaderRoute: typeof AdminFinanzasRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/eventos': {
      id: '/admin/eventos'
      path: '/eventos'
      fullPath: '/admin/eventos'
      preLoaderRoute: typeof AdminEventosRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/cuenta/retiro/': {
      id: '/cuenta/retiro/'
      path: '/'
      fullPath: '/cuenta/retiro/'
      preLoaderRoute: typeof CuentaRetiroIndexRouteImport
      parentRoute: typeof CuentaRetiroRouteRoute
    }
    '/cuenta/reportes/': {
      id: '/cuenta/reportes/'
      path: '/reportes'
      fullPath: '/cuenta/reportes/'
      preLoaderRoute: typeof CuentaReportesIndexRouteImport
      parentRoute: typeof CuentaRouteRoute
    }
    '/cuenta/publicaciones/': {
      id: '/cuenta/publicaciones/'
      path: '/publicaciones'
      fullPath: '/cuenta/publicaciones/'
      preLoaderRoute: typeof CuentaPublicacionesIndexRouteImport
      parentRoute: typeof CuentaRouteRoute
    }
    '/checkout/$orderId/': {
      id: '/checkout/$orderId/'
      path: '/checkout/$orderId'
      fullPath: '/checkout/$orderId/'
      preLoaderRoute: typeof CheckoutOrderIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tareas-programadas/': {
      id: '/admin/tareas-programadas/'
      path: '/tareas-programadas'
      fullPath: '/admin/tareas-programadas/'
      preLoaderRoute: typeof AdminTareasProgramadasIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/retiros/': {
      id: '/admin/retiros/'
      path: '/'
      fullPath: '/admin/retiros/'
      preLoaderRoute: typeof AdminRetirosIndexRouteImport
      parentRoute: typeof AdminRetirosRouteRoute
    }
    '/admin/reportes/': {
      id: '/admin/reportes/'
      path: '/reportes'
      fullPath: '/admin/reportes/'
      preLoaderRoute: typeof AdminReportesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/finanzas/': {
      id: '/admin/finanzas/'
      path: '/'
      fullPath: '/admin/finanzas/'
      preLoaderRoute: typeof AdminFinanzasIndexRouteImport
      parentRoute: typeof AdminFinanzasRouteRoute
    }
    '/admin/eventos/': {
      id: '/admin/eventos/'
      path: '/'
      fullPath: '/admin/eventos/'
      preLoaderRoute: typeof AdminEventosIndexRouteImport
      parentRoute: typeof AdminEventosRouteRoute
    }
    '/eventos/en/$location': {
      id: '/eventos/en/$location'
      path: '/eventos/en/$location'
      fullPath: '/eventos/en/$location'
      preLoaderRoute: typeof EventosEnLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuenta/retiro/$payoutId': {
      id: '/cuenta/retiro/$payoutId'
      path: '/$payoutId'
      fullPath: '/cuenta/retiro/$payoutId'
      preLoaderRoute: typeof CuentaRetiroPayoutIdRouteImport
      parentRoute: typeof CuentaRetiroRouteRoute
    }
    '/cuenta/reportes/$reportId': {
      id: '/cuenta/reportes/$reportId'
      path: '/reportes/$reportId'
      fullPath: '/cuenta/reportes/$reportId'
      preLoaderRoute: typeof CuentaReportesReportIdRouteImport
      parentRoute: typeof CuentaRouteRoute
    }
    '/cuenta/publicaciones/$listingId': {
      id: '/cuenta/publicaciones/$listingId'
      path: '/publicaciones/$listingId'
      fullPath: '/cuenta/publicaciones/$listingId'
      preLoaderRoute: typeof CuentaPublicacionesListingIdRouteImport
      parentRoute: typeof CuentaRouteRoute
    }
    '/checkout/$orderId/success': {
      id: '/checkout/$orderId/success'
      path: '/checkout/$orderId/success'
      fullPath: '/checkout/$orderId/success'
      preLoaderRoute: typeof CheckoutOrderIdSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/retiros/$payoutId': {
      id: '/admin/retiros/$payoutId'
      path: '/$payoutId'
      fullPath: '/admin/retiros/$payoutId'
      preLoaderRoute: typeof AdminRetirosPayoutIdRouteImport
      parentRoute: typeof AdminRetirosRouteRoute
    }
    '/admin/reportes/$reportId': {
      id: '/admin/reportes/$reportId'
      path: '/reportes/$reportId'
      fullPath: '/admin/reportes/$reportId'
      preLoaderRoute: typeof AdminReportesReportIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/eventos/$eventId': {
      id: '/admin/eventos/$eventId'
      path: '/$eventId'
      fullPath: '/admin/eventos/$eventId'
      preLoaderRoute: typeof AdminEventosEventIdRouteImport
      parentRoute: typeof AdminEventosRouteRoute
    }
    '/admin/finanzas/liquidaciones/$settlementId': {
      id: '/admin/finanzas/liquidaciones/$settlementId'
      path: '/liquidaciones/$settlementId'
      fullPath: '/admin/finanzas/liquidaciones/$settlementId'
      preLoaderRoute: typeof AdminFinanzasLiquidacionesSettlementIdRouteImport
      parentRoute: typeof AdminFinanzasRouteRoute
    }
  }
}

interface AdminEventosRouteRouteChildren {
  AdminEventosEventIdRoute: typeof AdminEventosEventIdRoute
  AdminEventosIndexRoute: typeof AdminEventosIndexRoute
}

const AdminEventosRouteRouteChildren: AdminEventosRouteRouteChildren = {
  AdminEventosEventIdRoute: AdminEventosEventIdRoute,
  AdminEventosIndexRoute: AdminEventosIndexRoute,
}

const AdminEventosRouteRouteWithChildren =
  AdminEventosRouteRoute._addFileChildren(AdminEventosRouteRouteChildren)

interface AdminFinanzasRouteRouteChildren {
  AdminFinanzasIndexRoute: typeof AdminFinanzasIndexRoute
  AdminFinanzasLiquidacionesSettlementIdRoute: typeof AdminFinanzasLiquidacionesSettlementIdRoute
}

const AdminFinanzasRouteRouteChildren: AdminFinanzasRouteRouteChildren = {
  AdminFinanzasIndexRoute: AdminFinanzasIndexRoute,
  AdminFinanzasLiquidacionesSettlementIdRoute:
    AdminFinanzasLiquidacionesSettlementIdRoute,
}

const AdminFinanzasRouteRouteWithChildren =
  AdminFinanzasRouteRoute._addFileChildren(AdminFinanzasRouteRouteChildren)

interface AdminRetirosRouteRouteChildren {
  AdminRetirosPayoutIdRoute: typeof AdminRetirosPayoutIdRoute
  AdminRetirosIndexRoute: typeof AdminRetirosIndexRoute
}

const AdminRetirosRouteRouteChildren: AdminRetirosRouteRouteChildren = {
  AdminRetirosPayoutIdRoute: AdminRetirosPayoutIdRoute,
  AdminRetirosIndexRoute: AdminRetirosIndexRoute,
}

const AdminRetirosRouteRouteWithChildren =
  AdminRetirosRouteRoute._addFileChildren(AdminRetirosRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminEventosRouteRoute: typeof AdminEventosRouteRouteWithChildren
  AdminFinanzasRouteRoute: typeof AdminFinanzasRouteRouteWithChildren
  AdminRetirosRouteRoute: typeof AdminRetirosRouteRouteWithChildren
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminVerificacionesRoute: typeof AdminVerificacionesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminReportesReportIdRoute: typeof AdminReportesReportIdRoute
  AdminReportesIndexRoute: typeof AdminReportesIndexRoute
  AdminTareasProgramadasIndexRoute: typeof AdminTareasProgramadasIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminEventosRouteRoute: AdminEventosRouteRouteWithChildren,
  AdminFinanzasRouteRoute: AdminFinanzasRouteRouteWithChildren,
  AdminRetirosRouteRoute: AdminRetirosRouteRouteWithChildren,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminVerificacionesRoute: AdminVerificacionesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminReportesReportIdRoute: AdminReportesReportIdRoute,
  AdminReportesIndexRoute: AdminReportesIndexRoute,
  AdminTareasProgramadasIndexRoute: AdminTareasProgramadasIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface CuentaRetiroRouteRouteChildren {
  CuentaRetiroPayoutIdRoute: typeof CuentaRetiroPayoutIdRoute
  CuentaRetiroIndexRoute: typeof CuentaRetiroIndexRoute
}

const CuentaRetiroRouteRouteChildren: CuentaRetiroRouteRouteChildren = {
  CuentaRetiroPayoutIdRoute: CuentaRetiroPayoutIdRoute,
  CuentaRetiroIndexRoute: CuentaRetiroIndexRoute,
}

const CuentaRetiroRouteRouteWithChildren =
  CuentaRetiroRouteRoute._addFileChildren(CuentaRetiroRouteRouteChildren)

interface CuentaRouteRouteChildren {
  CuentaRetiroRouteRoute: typeof CuentaRetiroRouteRouteWithChildren
  CuentaConfiguracionRoute: typeof CuentaConfiguracionRoute
  CuentaEntradasRoute: typeof CuentaEntradasRoute
  CuentaEstadoVerificacionRoute: typeof CuentaEstadoVerificacionRoute
  CuentaSubirEntradasRoute: typeof CuentaSubirEntradasRoute
  CuentaVerificarRoute: typeof CuentaVerificarRoute
  CuentaPublicacionesListingIdRoute: typeof CuentaPublicacionesListingIdRoute
  CuentaReportesReportIdRoute: typeof CuentaReportesReportIdRoute
  CuentaPublicacionesIndexRoute: typeof CuentaPublicacionesIndexRoute
  CuentaReportesIndexRoute: typeof CuentaReportesIndexRoute
}

const CuentaRouteRouteChildren: CuentaRouteRouteChildren = {
  CuentaRetiroRouteRoute: CuentaRetiroRouteRouteWithChildren,
  CuentaConfiguracionRoute: CuentaConfiguracionRoute,
  CuentaEntradasRoute: CuentaEntradasRoute,
  CuentaEstadoVerificacionRoute: CuentaEstadoVerificacionRoute,
  CuentaSubirEntradasRoute: CuentaSubirEntradasRoute,
  CuentaVerificarRoute: CuentaVerificarRoute,
  CuentaPublicacionesListingIdRoute: CuentaPublicacionesListingIdRoute,
  CuentaReportesReportIdRoute: CuentaReportesReportIdRoute,
  CuentaPublicacionesIndexRoute: CuentaPublicacionesIndexRoute,
  CuentaReportesIndexRoute: CuentaReportesIndexRoute,
}

const CuentaRouteRouteWithChildren = CuentaRouteRoute._addFileChildren(
  CuentaRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  CuentaRouteRoute: CuentaRouteRouteWithChildren,
  ContactoRoute: ContactoRoute,
  GarantiaRoute: GarantiaRoute,
  PoliticaDePrivacidadRoute: PoliticaDePrivacidadRoute,
  PreguntasFrecuentesRoute: PreguntasFrecuentesRoute,
  SitemapRoute: SitemapRoute,
  TerminosYCondicionesRoute: TerminosYCondicionesRoute,
  EntradasPublicarRoute: EntradasPublicarRoute,
  EventosSlugRoute: EventosSlugRoute,
  EventosEsteFinDeSemanaRoute: EventosEsteFinDeSemanaRoute,
  EventosHoyRoute: EventosHoyRoute,
  IngresarSplatRoute: IngresarSplatRoute,
  RegistrarseSplatRoute: RegistrarseSplatRoute,
  CheckoutOrderIdSuccessRoute: CheckoutOrderIdSuccessRoute,
  EventosEnLocationRoute: EventosEnLocationRoute,
  CheckoutOrderIdIndexRoute: CheckoutOrderIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
