/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PathlessLayoutRouteImport } from './routes/_pathlessLayout'
import { Route as CuentaRouteRouteImport } from './routes/cuenta/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegistrarseSplatRouteImport } from './routes/registrarse.$'
import { Route as IngresarSplatRouteImport } from './routes/ingresar.$'
import { Route as EventosEventIdRouteImport } from './routes/eventos/$eventId'
import { Route as EntradasPublicarRouteImport } from './routes/entradas/publicar'
import { Route as CuentaPublicacionesRouteImport } from './routes/cuenta/publicaciones'
import { Route as CuentaPerfilRouteImport } from './routes/cuenta/perfil'
import { Route as EntradasEditarListingIdRouteImport } from './routes/entradas/editar.$listingId'

const PathlessLayoutRoute = PathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentaRouteRoute = CuentaRouteRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrarseSplatRoute = RegistrarseSplatRouteImport.update({
  id: '/registrarse/$',
  path: '/registrarse/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IngresarSplatRoute = IngresarSplatRouteImport.update({
  id: '/ingresar/$',
  path: '/ingresar/$',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosEventIdRoute = EventosEventIdRouteImport.update({
  id: '/eventos/$eventId',
  path: '/eventos/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const EntradasPublicarRoute = EntradasPublicarRouteImport.update({
  id: '/entradas/publicar',
  path: '/entradas/publicar',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentaPublicacionesRoute = CuentaPublicacionesRouteImport.update({
  id: '/publicaciones',
  path: '/publicaciones',
  getParentRoute: () => CuentaRouteRoute,
} as any)
const CuentaPerfilRoute = CuentaPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => CuentaRouteRoute,
} as any)
const EntradasEditarListingIdRoute = EntradasEditarListingIdRouteImport.update({
  id: '/entradas/editar/$listingId',
  path: '/entradas/editar/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cuenta': typeof CuentaRouteRouteWithChildren
  '/cuenta/perfil': typeof CuentaPerfilRoute
  '/cuenta/publicaciones': typeof CuentaPublicacionesRoute
  '/entradas/publicar': typeof EntradasPublicarRoute
  '/eventos/$eventId': typeof EventosEventIdRoute
  '/ingresar/$': typeof IngresarSplatRoute
  '/registrarse/$': typeof RegistrarseSplatRoute
  '/entradas/editar/$listingId': typeof EntradasEditarListingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cuenta': typeof CuentaRouteRouteWithChildren
  '/cuenta/perfil': typeof CuentaPerfilRoute
  '/cuenta/publicaciones': typeof CuentaPublicacionesRoute
  '/entradas/publicar': typeof EntradasPublicarRoute
  '/eventos/$eventId': typeof EventosEventIdRoute
  '/ingresar/$': typeof IngresarSplatRoute
  '/registrarse/$': typeof RegistrarseSplatRoute
  '/entradas/editar/$listingId': typeof EntradasEditarListingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cuenta': typeof CuentaRouteRouteWithChildren
  '/_pathlessLayout': typeof PathlessLayoutRoute
  '/cuenta/perfil': typeof CuentaPerfilRoute
  '/cuenta/publicaciones': typeof CuentaPublicacionesRoute
  '/entradas/publicar': typeof EntradasPublicarRoute
  '/eventos/$eventId': typeof EventosEventIdRoute
  '/ingresar/$': typeof IngresarSplatRoute
  '/registrarse/$': typeof RegistrarseSplatRoute
  '/entradas/editar/$listingId': typeof EntradasEditarListingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cuenta'
    | '/cuenta/perfil'
    | '/cuenta/publicaciones'
    | '/entradas/publicar'
    | '/eventos/$eventId'
    | '/ingresar/$'
    | '/registrarse/$'
    | '/entradas/editar/$listingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cuenta'
    | '/cuenta/perfil'
    | '/cuenta/publicaciones'
    | '/entradas/publicar'
    | '/eventos/$eventId'
    | '/ingresar/$'
    | '/registrarse/$'
    | '/entradas/editar/$listingId'
  id:
    | '__root__'
    | '/'
    | '/cuenta'
    | '/_pathlessLayout'
    | '/cuenta/perfil'
    | '/cuenta/publicaciones'
    | '/entradas/publicar'
    | '/eventos/$eventId'
    | '/ingresar/$'
    | '/registrarse/$'
    | '/entradas/editar/$listingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CuentaRouteRoute: typeof CuentaRouteRouteWithChildren
  PathlessLayoutRoute: typeof PathlessLayoutRoute
  EntradasPublicarRoute: typeof EntradasPublicarRoute
  EventosEventIdRoute: typeof EventosEventIdRoute
  IngresarSplatRoute: typeof IngresarSplatRoute
  RegistrarseSplatRoute: typeof RegistrarseSplatRoute
  EntradasEditarListingIdRoute: typeof EntradasEditarListingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuenta': {
      id: '/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof CuentaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrarse/$': {
      id: '/registrarse/$'
      path: '/registrarse/$'
      fullPath: '/registrarse/$'
      preLoaderRoute: typeof RegistrarseSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingresar/$': {
      id: '/ingresar/$'
      path: '/ingresar/$'
      fullPath: '/ingresar/$'
      preLoaderRoute: typeof IngresarSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/$eventId': {
      id: '/eventos/$eventId'
      path: '/eventos/$eventId'
      fullPath: '/eventos/$eventId'
      preLoaderRoute: typeof EventosEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entradas/publicar': {
      id: '/entradas/publicar'
      path: '/entradas/publicar'
      fullPath: '/entradas/publicar'
      preLoaderRoute: typeof EntradasPublicarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuenta/publicaciones': {
      id: '/cuenta/publicaciones'
      path: '/publicaciones'
      fullPath: '/cuenta/publicaciones'
      preLoaderRoute: typeof CuentaPublicacionesRouteImport
      parentRoute: typeof CuentaRouteRoute
    }
    '/cuenta/perfil': {
      id: '/cuenta/perfil'
      path: '/perfil'
      fullPath: '/cuenta/perfil'
      preLoaderRoute: typeof CuentaPerfilRouteImport
      parentRoute: typeof CuentaRouteRoute
    }
    '/entradas/editar/$listingId': {
      id: '/entradas/editar/$listingId'
      path: '/entradas/editar/$listingId'
      fullPath: '/entradas/editar/$listingId'
      preLoaderRoute: typeof EntradasEditarListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CuentaRouteRouteChildren {
  CuentaPerfilRoute: typeof CuentaPerfilRoute
  CuentaPublicacionesRoute: typeof CuentaPublicacionesRoute
}

const CuentaRouteRouteChildren: CuentaRouteRouteChildren = {
  CuentaPerfilRoute: CuentaPerfilRoute,
  CuentaPublicacionesRoute: CuentaPublicacionesRoute,
}

const CuentaRouteRouteWithChildren = CuentaRouteRoute._addFileChildren(
  CuentaRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CuentaRouteRoute: CuentaRouteRouteWithChildren,
  PathlessLayoutRoute: PathlessLayoutRoute,
  EntradasPublicarRoute: EntradasPublicarRoute,
  EventosEventIdRoute: EventosEventIdRoute,
  IngresarSplatRoute: IngresarSplatRoute,
  RegistrarseSplatRoute: RegistrarseSplatRoute,
  EntradasEditarListingIdRoute: EntradasEditarListingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
